import {test} from 'node:test';
import assert from 'node:assert/strict';
import initSql from '../native/vendor/sql-asm.js';
import {NursingSQL} from '../native/sql.ts';
import {schema} from '../native/schema.ts';
import {SnapshotStore} from '../native/snapshots.ts';
import {NativeEngine} from '../native/engine.ts';
import {encodeBytes,decodeBytes} from '../native/encoding.ts';
const SQL=await initSql();
class MemoryStorage{data=new Map<string,any>();failHead=false;async get<T>(key:string){return this.data.get(key) as T|undefined;}async put(key:string,value:unknown){if(this.failHead&&key==='nursing:head')throw new Error('Storage Failure');this.data.set(key,structuredClone(value));}async delete(key:string){return this.data.delete(key);}}
const users:Record<string,any>={office:{id:'office',email:'office@example.test',full_name:'Agency Staff'},nurse:{id:'nurse',email:'nurse@example.test',full_name:'Test Nurse'},other:{id:'other',email:'other@example.test'},facility:{id:'facility',email:'facility@example.test'}};
const now=Date.now(),date=new Date(now-86400000).toISOString().slice(0,10);
const shift={facility:'Facility A',address:'100 Main Street',facilityType:'Hospital',state:'NC',role:'RN',start:now+600000,end:now+8*3600000,timeZone:'America/New_York',lat:35,lon:-80,radius:100,baseCents:4000,differentialCents:500,urgentCents:0,urgentUnit:'hour',requirements:['license','bls','tb','physical'],notes:{}};
const credential={role:'RN',states:['NC'],expires:{license:now+365*86400000,bls:now+180*86400000,tb:now+180*86400000,physical:now+180*86400000},issuedDates:{bls:date,tb:date,physical:date},sourceNote:'Verified For Test'};
async function fixture(seed?:(db:NursingSQL)=>Promise<void>){const storage=new MemoryStorage(),db=new NursingSQL(new SQL.Database());db.sqlite.run(schema);for(const id of ['nurse','other']){await db.prepare('INSERT INTO applications VALUES(?,?,?,?,?)').bind(id,users[id].email,'draft','{"firstName":"Test","lastName":"Nurse"}',now).run();await db.prepare('INSERT INTO compliance VALUES(?,?,?,?)').bind(id,JSON.stringify(credential),'office',now).run();await db.prepare('INSERT INTO settings VALUES(?,?)').bind('employee_hired:'+id,'{"hired":true}').run();}await db.prepare("INSERT INTO live_shifts(id,data,status,created_at) VALUES(?,?,'open',?)").bind('shift-1',JSON.stringify(shift),now).run();await seed?.(db);await new SnapshotStore(storage).commit(db.export());db.sqlite.close();const privateFiles=new Map<string,Uint8Array>();let uploads=0,reads=0;const client={asServiceRole:{integrations:{Core:{async UploadPrivateFile({file}:any){uploads++;const uri='private/'+crypto.randomUUID();privateFiles.set(uri,new Uint8Array(await file.arrayBuffer()));return {file_uri:uri};},async CreateFileSignedUrl({file_uri}:any){reads++;if(!privateFiles.has(file_uri))throw new Error('Missing Private File');return {signed_url:'https://files.example.test/'+file_uri};}}}}};const verify=async(token:string)=>{if(!users[token])throw new Error('Unverified Token');return users[token];};const secrets={STAFF_AUTH_IDS:'office',STAFF_EMAILS:'office@example.test'};const engine=new NativeEngine(SQL,storage,client,secrets,verify);await engine.initialize();return {engine,storage,client,verify,secrets,privateFiles,uploads:()=>uploads,reads:()=>reads,restart:()=>new NativeEngine(SQL,storage,client,secrets,verify),async inspect(){const bytes=await new SnapshotStore(storage).read();return new NursingSQL(new SQL.Database(bytes!));}};}
async function request(f:any,user:string,path:string,data?:any,id=crypto.randomUUID(),token=user){const reply=await f.engine.run(user,{id,path,method:data===undefined?'GET':'POST',authToken:token,contentType:data===undefined?undefined:'application/json',body:data===undefined?undefined:encodeBytes(new TextEncoder().encode(JSON.stringify(data)))});const bytes=decodeBytes(reply.body);const text=new TextDecoder().decode(bytes);return {status:reply.status,headers:reply.headers,bytes,body:reply.headers['content-type']?.includes('json')?JSON.parse(text):text};}
test('Uses verified platform sessions and explicit staff IDs; ignores claimed browser roles and email-only privileges',async()=>{const f=await fixture();assert.equal((await request(f,'nurse','/api/session')).body.office,false);assert.equal((await request(f,'office','/api/session')).body.office,true);await assert.rejects(request(f,'office','/api/session',undefined,crypto.randomUUID(),'nurse'),/verified/i);await assert.rejects(request(f,'nurse','/api/session',undefined,crypto.randomUUID(),'forged'),/unverified/i);assert.equal((await request(f,'nurse','/api/workflows',{action:'contact',email:'bad@example.test',role:'admin',authId:'office'})).status,403);});
test('Atomic booking permits exactly one concurrent applicant and persists across actor restarts',async()=>{const f=await fixture();const responses=await Promise.all([request(f,'nurse','/api/workflows',{action:'accept',shiftId:'shift-1'}),request(f,'other','/api/workflows',{action:'accept',shiftId:'shift-1'})]);assert.deepEqual(responses.map(r=>r.status).sort(),[200,400]);const db=await f.inspect();assert.equal((await db.prepare('SELECT * FROM assignments').all()).results.length,1);f.engine=f.restart();assert.equal((await request(f,'nurse','/api/workflows')).body.shifts[0].status,'filled');});
test('Duplicate transport request IDs do not duplicate a committed booking',async()=>{const f=await fixture(),id=crypto.randomUUID();const first=await request(f,'nurse','/api/workflows',{action:'accept',shiftId:'shift-1'},id);const second=await request(f,'nurse','/api/workflows',{action:'accept',shiftId:'shift-1'},id);assert.equal(first.status,200);assert.deepEqual(second,first);const db=await f.inspect();assert.equal((await db.prepare('SELECT * FROM workflow_events').all()).results.length,1);});
test('Credential expiry, hiring approval, DNR, and inactive status block booking on the backend',async()=>{for(const reason of ['expired','unhired','dnr','inactive']){const f=await fixture(async db=>{if(reason==='expired')await db.prepare('UPDATE compliance SET data=? WHERE user_id=?').bind(JSON.stringify({...credential,expires:{...credential.expires,license:now-1}}),'nurse').run();if(reason==='unhired')await db.prepare('DELETE FROM settings WHERE key=?').bind('employee_hired:nurse').run();if(reason==='inactive')await db.prepare('INSERT INTO employee_status VALUES(?,?,?,?,?,?,?,?)').bind('nurse','quit','2026-01-01','2026-10-01','Private Note','office',now,0).run();if(reason==='dnr')await db.prepare('INSERT INTO facility_reports(id,user_id,assignment_id,facility,quarter_key,kind,status,data,submitted_by,submitted_at) VALUES(?,?,?,?,?,?,?,?,?,?)').bind('dnr','nurse','a','Facility A','2026-Q4','dnr','active','{}','office',now).run();});const r=await request(f,'nurse','/api/workflows',{action:'accept',shiftId:'shift-1'});assert.ok(r.status>=400,reason);const db=await f.inspect();assert.equal((await db.prepare('SELECT * FROM assignments').all()).results.length,0,reason);}});
test('Snapshot publication failure rolls back the in-memory booking and leaves durable data unchanged',async()=>{const f=await fixture();f.storage.failHead=true;await assert.rejects(request(f,'nurse','/api/workflows',{action:'accept',shiftId:'shift-1'}),/Storage Failure/);f.storage.failHead=false;assert.equal((await request(f,'other','/api/workflows',{action:'accept',shiftId:'shift-1'})).status,200);const db=await f.inspect();assert.equal((await db.prepare('SELECT user_id FROM assignments').first())?.user_id,'other');});
test('Inactive employees retain only own payroll and basic profile; all other route groups deny access',async()=>{const f=await fixture(async db=>{await db.prepare('INSERT INTO employee_status VALUES(?,?,?,?,?,?,?,?)').bind('nurse','terminated','2026-01-01','2026-10-01','Agency-Only Note','office',now,0).run();for(const kind of ['paystub','w2','license'])await db.prepare('INSERT INTO documents VALUES(?,?,?,?,?,?,?,?,?)').bind(crypto.randomUUID(),'nurse',kind,kind+'.pdf','application/pdf',4,'key','backup',now).run();});for(const name of ['application','workflows','incentives','quarterly-contest','no-call-no-show','facility-feedback','facility-contract','facility-contract/pdf','merch','merch/shop','home','training'])assert.equal((await request(f,'nurse','/api/'+name)).status,403,name);assert.deepEqual((await request(f,'nurse','/api/documents')).body.documents.map((d:any)=>d.kind).sort(),['paystub','w2']);const profile=(await request(f,'nurse','/api/employment?userId=other')).body;assert.equal(profile.status,'terminated');assert.equal(profile.note,undefined);assert.equal(profile.employees,undefined);});
test('Private files require record ownership before any storage or signed URL operation',async()=>{const id=crypto.randomUUID();const f=await fixture(async db=>{await db.prepare('INSERT INTO documents VALUES(?,?,?,?,?,?,?,?,?)').bind(id,'nurse','license','License.pdf','application/pdf',4,'key','backup',now).run();});assert.equal((await request(f,'other','/api/documents/'+id)).status,404);assert.equal(f.reads(),0);assert.equal(f.uploads(),0);});
test('GPS and RN/LPN signoff requirements remain enforced through native routes',async()=>{const f=await fixture();assert.equal((await request(f,'nurse','/api/workflows',{action:'accept',shiftId:'shift-1'})).status,200);const body={action:'clockIn',shiftId:'shift-1',employeeName:'Test Nurse',supervisorName:'Test Supervisor',supervisorTitle:'CNA',signature:[[[0,0],[.2,.2],[.5,.5]]],location:{lat:35,lon:-80,accuracy:10,at:Date.now()}};assert.equal((await request(f,'nurse','/api/workflows',body)).status,400);assert.equal((await request(f,'nurse','/api/workflows',{...body,supervisorTitle:'RN',location:{...body.location,lat:36}})).status,400);assert.equal((await request(f,'nurse','/api/workflows',{...body,supervisorTitle:'RN'})).status,200);});
test('No-call/no-show produces automatic seven-day suspension; employee cannot revoke it',async()=>{const f=await fixture(async db=>{await db.prepare('UPDATE live_shifts SET data=? WHERE id=?').bind(JSON.stringify({...shift,start:now-600000}),'shift-1').run();await db.prepare('INSERT INTO assignments VALUES(?,?,?,?,?,?)').bind('absence-assignment','shift-1','nurse','accepted','{}',now).run();await db.prepare('INSERT INTO facility_access VALUES(?,?,?,?,?,?)').bind('grant','facility@example.test','Facility A',1,'office',now).run();});const report={noCallConfirmed:true,evaluatorName:'Facility Supervisor',evaluatorTitle:'RN',details:'Did not attend or notify the facility.'};assert.equal((await request(f,'facility','/api/no-call-no-show',{action:'report',assignmentId:'absence-assignment',report})).status,200);const absence=(await request(f,'nurse','/api/no-call-no-show')).body;assert.equal(absence.suspension.suspended,true);assert.equal(absence.incidents[0].days,7);assert.equal((await request(f,'nurse','/api/no-call-no-show',{action:'review',id:'absence-assignment',status:'revoked',note:'Self revoke',version:0})).status,403);});
test('Snapshot corruption fails closed rather than silently creating a new empty database',async()=>{const f=await fixture();const head=await f.storage.get<any>('nursing:head');f.storage.data.set('nursing:snapshot:'+head.id+':0','CORRUPTED');await assert.rejects(f.restart().initialize());});
test('Native private upload, authorized preview, and staff backup export work through the converted adapter',async()=>{const f=await fixture();const file=new File([new Uint8Array([37,80,68,70,45,49])],'Question.pdf',{type:'application/pdf'});const form=new FormData();form.set('kind','attachment');form.set('file',file);const encoded=new Request('https://always-nursing.internal/api/documents',{method:'POST',body:form});const reply=await f.engine.run('nurse',{id:crypto.randomUUID(),path:'/api/documents',method:'POST',authToken:'nurse',contentType:encoded.headers.get('content-type')!,body:encodeBytes(new Uint8Array(await encoded.arrayBuffer()))});assert.equal(reply.status,201);const doc=JSON.parse(new TextDecoder().decode(decodeBytes(reply.body)));assert.equal(f.uploads(),2);const original=globalThis.fetch;try{globalThis.fetch=async(input:any)=>{const url=new URL(String(input));if(url.hostname!=='files.example.test')throw new Error('Unexpected Request');const bytes=f.privateFiles.get(url.pathname.slice(1));return new Response(bytes||null,{status:bytes?200:404});};const preview=await request(f,'nurse','/api/documents/'+doc.id+'?view=1');assert.equal(preview.status,200);assert.equal(preview.headers['content-type'],'application/pdf');assert.deepEqual(Array.from(preview.bytes),[37,80,68,70,45,49]);assert.equal((await request(f,'other','/api/documents/'+doc.id)).status,404);assert.equal(f.reads(),1);}finally{globalThis.fetch=original;}assert.equal((await request(f,'nurse','/api/native-backup')).status,403);const backup=await request(f,'office','/api/native-backup');assert.equal(backup.status,200);assert.equal(new TextDecoder().decode(backup.bytes.slice(0,15)),'SQLite format 3');const restored=new NursingSQL(new SQL.Database(backup.bytes));assert.equal((await restored.prepare('SELECT * FROM documents').all()).results.length,1);});
test('All dashboard record collections execute on the portable native SQL driver',async()=>{const f=await fixture();for(const user of ['nurse','office'])for(const name of ['application','documents','workflows','referrals','training','facility-inquiries','facility-contract','employment','merch','theme','no-call-no-show','facility-feedback','home','quarterly-contest','incentives','demo-links','shift-preview']){const result=await request(f,user,'/api/'+name);assert.ok(result.status<500,user+' '+name+' '+JSON.stringify(result.body));}});
test('Additive schema upgrades preserve existing records; old code refuses newer schemas',async()=>{const f=await fixture();const db=await f.inspect();assert.equal((await db.prepare('PRAGMA user_version').first())?.user_version,1);assert.equal((await db.prepare('SELECT * FROM applications').all()).results.length,2);db.sqlite.run('PRAGMA user_version=99');await new SnapshotStore(f.storage).commit(db.export());await assert.rejects(f.restart().initialize(),/Newer Than/);const after=await f.inspect();assert.equal((await after.prepare('SELECT * FROM applications').all()).results.length,2);});
test('Agency privileges follow refreshed server configuration, including revocation',async()=>{const f=await fixture();let ids='office';f.engine=new NativeEngine(SQL,f.storage,f.client,()=>({...f.secrets,STAFF_AUTH_IDS:ids}),f.verify);assert.equal((await request(f,'office','/api/session')).body.office,true);ids='';assert.equal((await request(f,'office','/api/session')).body.office,false);assert.equal((await request(f,'office','/api/workflows',{action:'contact',email:'staff@example.test'})).status,403);});
