import {validateFeedback,evaluationCriteria,permittedReview,blocksBooking,blocksContest,reviewedInQuarter} from '../lib/facility-feedback.ts';
import {contestQuarter,contestCandidate,drawWinners,unbiasedIndex,type Tier} from '../lib/quarterly-contest.ts';
import {incentivePeriod,evaluateIncentive,countedShift,type IncentiveShift} from '../lib/incentives.ts';
import {validateContractPdf,contractSummary} from '../lib/facility-contract.ts';
import {test} from 'node:test';
import assert from 'node:assert/strict';
import {visibleShift,validateInstructions,instructionItems,eligibility,validateLocation,applyTimeAction,validSignature,hoursWorked,paySummary,scopedEmployee,canReadDocument,canPublishPayroll,type Shift,type Compliance,type Signoff} from '../lib/workflow.ts';
const now=Date.now();const shift:Shift={facility:'Test facility',address:'Test address',state:'NC',role:'RN',start:now+3600000,end:now+9*3600000,timeZone:'America/New_York',baseCents:4500,differentialCents:500,urgentCents:1000,urgentUnit:'hour',lat:35.2271,lon:-80.8431,radius:150,requirements:[],source:'test'};
const verified:Compliance={issuedDates:Object.fromEntries(['tb','bls','physical'].map(k=>[k,new Date(now).toISOString().slice(0,10)])),role:'RN',states:['NC'],expires:Object.fromEntries(['license','bls','tb','physical'].map(k=>[k,shift.end+86400000])),sourceNote:'Test only'};
const sign:Signoff & {location:NonNullable<Signoff["location"]>}={employeeName:'Test Employee',supervisorName:'Test Supervisor',signature:[[[.1,.1],[.2,.3],[.4,.4]]],at:now,location:{lat:shift.lat,lon:shift.lon,accuracy:20,at:now}};
test('Missing compliance cannot book',()=>assert.equal(eligibility(null,shift,now).length,1));
test('All verified credentials and jurisdiction pass',()=>assert.deepEqual(eligibility(verified,shift,now),[]));
test('Expiry before end of shift blocks',()=>assert(eligibility({...verified,expires:{...verified.expires,bls:shift.end-1}},shift,now).some(x=>x.includes('BLS'))));
test('Wrong role and license state block',()=>assert.equal(eligibility({...verified,role:'LPN',states:['SC']},shift,now).length,2));
test('Facility-specific requirements are enforced',()=>assert(eligibility(verified,{...shift,requirements:['acls']},now).some(x=>x.includes('ACLS'))));
test('Accurate location inside boundary passes',()=>assert.equal(validateLocation(sign.location,shift,now),0));
test('Outside boundary fails',()=>assert.throws(()=>validateLocation({...sign.location,lat:36},shift,now),/boundary/));
test('Stale and inaccurate GPS fail',()=>{assert.throws(()=>validateLocation({...sign.location,at:now-61000},shift,now),/older/);assert.throws(()=>validateLocation({...sign.location,accuracy:120},shift,now),/accuracy/)});
test('Accuracy uncertainty cannot overlap boundary',()=>assert.throws(()=>validateLocation({...sign.location,lat:shift.lat+.0012,accuracy:30},shift,now),/boundary/));
test('Blank, malformed and excessive signatures fail',()=>{assert.equal(validSignature([]),false);assert.equal(validSignature([[[2,.1],[.2,.3],[.4,.4]]]),false);assert.equal(validSignature(sign.signature),true)});
test('Cannot clock out without clocking in',()=>assert.throws(()=>applyTimeAction(null,'clockOut',now,sign,true),/clocked/));
test('Duplicate clock-in cannot overwrite evidence',()=>{const r=applyTimeAction(null,'clockIn',now,sign);assert.throws(()=>applyTimeAction(r,'clockIn',now,sign),/already/)});
test('No-break must be explicit at signed checkout',()=>{const r=applyTimeAction(null,'clockIn',now,sign);assert.throws(()=>applyTimeAction(r,'clockOut',now+1000,sign,false),/no break/);const end=applyTimeAction(r,'clockOut',now+3600000,{...sign,at:now+3600000},true);assert.equal(end.noBreak,true);assert.equal(end.out?.supervisorName,'Test Supervisor')});
test('Active break prevents checkout; end break records exact interval',()=>{let r=applyTimeAction(null,'clockIn',now,sign);r=applyTimeAction(r,'breakStart',now+3600000);assert.throws(()=>applyTimeAction(r,'clockOut',now+7200000,sign,false),/End the active/);r=applyTimeAction(r,'breakEnd',now+5400000);r=applyTimeAction(r,'clockOut',now+8*3600000,{...sign,at:now+8*3600000},false);assert.deepEqual(hoursWorked(r),{elapsedHours:8,breakHours:.5,recordedWorkHours:7.5});assert.equal(r.noBreak,false)});
test('Cannot start two breaks or label recorded breaks no-break',()=>{let r=applyTimeAction(null,'clockIn',now,sign);r=applyTimeAction(r,'breakStart',now+1000);assert.throws(()=>applyTimeAction(r,'breakStart',now+2000),/already active/);r=applyTimeAction(r,'breakEnd',now+3000);assert.throws(()=>applyTimeAction(r,'clockOut',now+4000,sign,true),/cannot also/)});
test('Finished time records cannot be edited by new clock actions',()=>{const r=applyTimeAction(applyTimeAction(null,'clockIn',now,sign),'clockOut',now+3600000,{...sign,at:now+3600000},true);assert.throws(()=>applyTimeAction(r,'breakStart',now+4000000),/currently/)});
test('Pay differentiates hourly urgency from a one-time bonus',()=>{assert.deepEqual(paySummary(shift),{hourlyCents:6000,shiftBonusCents:0});assert.deepEqual(paySummary({...shift,urgentUnit:'shift'}),{hourlyCents:5000,shiftBonusCents:1000})});

test('An employee cannot switch accounts using a request parameter',()=>assert.equal(scopedEmployee('a',false,'b'),'a'));
test('Office can select an employee conversation',()=>assert.equal(scopedEmployee('office',true,'b'),'b'));
test('Private document access denies other employees',()=>{assert.equal(canReadDocument('a','b',false),false);assert.equal(canReadDocument('a','a',false),true);assert.equal(canReadDocument('office','b',true),true)});
test('Only office publishes paystubs and W-2s',()=>{assert.equal(canPublishPayroll(false,'w2'),false);assert.equal(canPublishPayroll(false,'paystub'),false);assert.equal(canPublishPayroll(true,'w2'),true);assert.equal(canPublishPayroll(false,'attachment'),true)});

test('Facility instructions are restricted to office or assigned employees',()=>{const s={...shift,notes:{medication:'Ask charge nurse for access'},facilityType:'LTCF'};assert.equal(visibleShift(s,false,false).notes,undefined);assert.deepEqual(visibleShift(s,false,true).notes,s.notes);assert.deepEqual(visibleShift(s,true,false).notes,s.notes);assert.ok(s.notes)});
test('Instructions are bounded and reject unknown sections',()=>{assert.throws(()=>validateInstructions({unknown:'test'}));assert.throws(()=>validateInstructions({lab:'x'.repeat(3001)}));assert.throws(()=>validateInstructions({lab:Array(32).fill('item').join('\n')}));assert.deepEqual(validateInstructions({lab:'  Call lab  '}),{lab:'Call lab'})});
test('Checklist item identifiers survive unrelated additions and detect changed text',()=>{const a=instructionItems({lab:'Call lab',admission:'Review admission'}),b=instructionItems({lab:'Call lab',admission:'Review admission',xray:'Call radiology'});assert.equal(a[0].id,b[0].id);assert.notEqual(a[0].id,instructionItems({lab:'Updated lab procedure'})[0].id);assert.equal(instructionItems({lab:'\n \n'}).length,0)});

test('Contract uploads require a complete PDF header and end marker',()=>{assert.doesNotThrow(()=>validateContractPdf(new TextEncoder().encode('%PDF-1.7\ncontent\n%%EOF')));assert.throws(()=>validateContractPdf(new TextEncoder().encode('Not a PDF %%EOF')));assert.throws(()=>validateContractPdf(new TextEncoder().encode('%PDF-1.7 truncated')));assert.throws(()=>validateContractPdf(new Uint8Array(5_000_001)))});
test('Facility contract metadata never exposes private storage keys',()=>{const c={id:'v1',filename:'contract.pdf',version:'1',bytes:40,uploadedAt:1,objectKey:'private/key',backupKey:'backup/key'};assert.deepEqual(contractSummary(c),{id:'v1',filename:'contract.pdf',version:'1',bytes:40,uploadedAt:1});assert.equal('objectKey' in contractSummary(c),false)});

test('Incentive periods start January 1 Eastern and reset every 14 calendar days',()=>{const p=incentivePeriod(Date.parse('2026-01-01T00:00:00-05:00'));assert.equal(p.key,'2026-01');assert.equal(p.start,Date.parse('2026-01-01T00:00:00-05:00'));assert.equal(p.end,Date.parse('2026-01-15T00:00:00-05:00'));assert.equal(incentivePeriod(p.end).key,'2026-02');assert.equal(incentivePeriod(p.start-1).key,'2025-27')});
test('Incentive periods handle DST and leap-year short year-end periods',()=>{const p=incentivePeriod(Date.parse('2026-03-08T12:00:00-04:00'));assert.equal(p.days,14);assert.equal(p.end-p.start,14*86400000-3600000);assert.equal(incentivePeriod(Date.parse('2028-12-31T12:00:00-05:00')).days,2);assert.equal(incentivePeriod(Date.parse('2026-12-31T12:00:00-05:00')).days,1)});
const bonusStart=Date.parse('2026-01-02T07:00:00-05:00'),bonusEnd=bonusStart+8*3600000,bonusPeriod=incentivePeriod(bonusStart);
const bonusShift:IncentiveShift={assignmentId:'shift:a',userId:'a',name:'Employee A',facility:'Facility',start:bonusStart,end:bonusEnd,state:'accepted',status:'filled',updatedAt:bonusStart-1,clockIn:bonusStart,clockOut:bonusEnd};
test('The $25 bonus is unavailable until the complete period closes',()=>{const active=evaluateIncentive(bonusPeriod,[bonusShift],bonusEnd+1);assert.equal(active.progress,100);assert.equal(active.eligible,false);const closed=evaluateIncentive(bonusPeriod,[bonusShift],bonusPeriod.end);assert.equal(closed.eligible,true);assert.equal(closed.amountCents,2500)});
test('On-time check-in fills half the bar and on-time sign-out completes it',()=>{assert.equal(evaluateIncentive(bonusPeriod,[{...bonusShift,clockOut:undefined}],bonusStart).progress,50);assert.equal(evaluateIncentive(bonusPeriod,[bonusShift],bonusEnd).progress,100)});
test('Late check-in, early/late checkout, or missing attendance blocks the bonus',()=>{for(const s of [{...bonusShift,clockIn:bonusStart+60000},{...bonusShift,clockOut:bonusEnd-1},{...bonusShift,clockOut:bonusEnd+60000},{...bonusShift,clockIn:undefined,clockOut:undefined}]){const result=evaluateIncentive(bonusPeriod,[s],bonusPeriod.end);assert.equal(result.eligible,false);assert.equal(result.failed,true)}});
test('Every assigned shift must pass and no shifts cannot earn cash',()=>{assert.equal(evaluateIncentive(bonusPeriod,[],bonusPeriod.end).amountCents,0);assert.equal(evaluateIncentive(bonusPeriod,[bonusShift,{...bonusShift,assignmentId:'missed',clockIn:undefined,clockOut:undefined}],bonusPeriod.end).eligible,false)});
test('Facility cancellations and pre-shift withdrawals are excluded; a missed shift cancelled late blocks',()=>{assert.equal(evaluateIncentive(bonusPeriod,[bonusShift,{...bonusShift,status:'cancelled',clockIn:undefined,clockOut:undefined}],bonusPeriod.end).eligible,true);assert.equal(countedShift({...bonusShift,state:'withdrawn'}),false);assert.equal(countedShift({...bonusShift,state:'employee_cancelled',updatedAt:bonusStart-1}),false);assert.equal(evaluateIncentive(bonusPeriod,[{...bonusShift,state:'employee_cancelled',updatedAt:bonusStart+1}],bonusPeriod.end).eligible,false)});
test('An overnight shift cannot earn before its scheduled end and next period starts at zero',()=>{const overnight={...bonusShift,start:bonusPeriod.end-3600000,end:bonusPeriod.end+7*3600000,clockIn:bonusPeriod.end-3600000,clockOut:undefined};assert.equal(evaluateIncentive(bonusPeriod,[overnight],bonusPeriod.end).closed,false);assert.equal(evaluateIncentive(incentivePeriod(bonusPeriod.end),[bonusShift],bonusPeriod.end).progress,0)});
test('A short year-end reset period cannot earn a two-week bonus',()=>{const start=Date.parse('2026-12-31T07:00:00-05:00'),end=start+3600000,p=incentivePeriod(start);assert.equal(evaluateIncentive(p,[{...bonusShift,start,end,clockIn:start,clockOut:end}],p.end).eligible,false)});

test('Contest quarters follow Eastern January/April/July/October boundaries',()=>{const q=contestQuarter(Date.parse('2026-01-01T00:00:00-05:00'));assert.equal(q.key,'2026-Q1');assert.equal(q.end,Date.parse('2026-04-01T00:00:00-04:00'));assert.equal(q.rosterAt,Date.parse('2026-03-25T00:00:00-04:00'));assert.equal(contestQuarter(q.end).key,'2026-Q2');assert.equal(contestQuarter(q.start-1).key,'2025-Q4')});
const awardQuarter=contestQuarter(bonusStart),awardNom={userId:'a',quarterKey:awardQuarter.key,category:'gold' as const,clearance:'clear'},excellentReview={userId:'a',quarterKey:awardQuarter.key,facility:'Facility',rating:'excellent'};
function candidate(rating='excellent',late=0,category:Tier='gold',dnr=false){const shifts=Array.from({length:Math.max(late,1)},(_,i)=>({...bonusShift,assignmentId:`shift${i}`,clockIn:bonusStart+(i<late?60000:0)}));return contestCandidate('a','Employee A',awardQuarter,shifts,[{...excellentReview,rating}],{...awardNom,category},dnr,awardQuarter.end)};
test('Golden Star requires excellent ratings, zero late shifts and verified no DNR',()=>{assert.equal(candidate().eligible,true);assert.equal(candidate('excellent',1).eligible,false);assert.equal(candidate('excellent',0,'gold',true).eligible,false);assert.equal(contestCandidate('a','A',awardQuarter,[bonusShift],[excellentReview],{...awardNom,clearance:'pending'},false,awardQuarter.end).eligible,false)});
test('Green Heart and Red Apple respect exact ranges, including five-late overlap',()=>{assert.equal(candidate('good',3,'green').eligible,true);assert.equal(candidate('good',5,'green').eligible,true);assert.equal(candidate('good',2,'green').eligible,false);assert.equal(candidate('good',6,'green').eligible,false);assert.equal(candidate('fair',5,'red').eligible,true);assert.equal(candidate('fair',8,'red').eligible,true);assert.equal(candidate('fair',9,'red').eligible,false);assert.equal(candidate('excellent',5,'green').eligible,false)});
test('Every worked facility needs evaluation and lowest rating controls entry',()=>{const shifts=[bonusShift,{...bonusShift,assignmentId:'other',facility:'Other'}];assert.equal(contestCandidate('a','A',awardQuarter,shifts,[excellentReview],awardNom,false,awardQuarter.end).eligible,false);const c=contestCandidate('a','A',awardQuarter,shifts,[excellentReview,{...excellentReview,facility:'Other',rating:'fair'}],awardNom,false,awardQuarter.end);assert.equal(c.rating,'fair');assert.equal(c.eligible,false)});
test('Missing attendance and early checkout prevent drawing entry; late shift counted once',()=>{assert.equal(contestCandidate('a','A',awardQuarter,[{...bonusShift,clockOut:undefined}],[excellentReview],awardNom,false,awardQuarter.end).eligible,false);assert.equal(contestCandidate('a','A',awardQuarter,[{...bonusShift,clockOut:bonusEnd-1}],[excellentReview],awardNom,false,awardQuarter.end).eligible,false);const c=contestCandidate('a','A',awardQuarter,[{...bonusShift,clockIn:bonusStart+60000,clockOut:bonusEnd+60000}],[excellentReview],awardNom,false,awardQuarter.end);assert.equal(c.late,1)});
test('Quarter rollover clears nomination icon and entries from the prior quarter',()=>{const next=contestQuarter(awardQuarter.end);const c=contestCandidate('a','A',next,[bonusShift],[excellentReview],undefined,false,next.start);assert.equal(c.category,null);assert.equal(c.eligible,false)});
test('Drawing picks one candidate per tier, excludes ineligible staff, and leaves empty tiers unawarded',()=>{const pool=[candidate(),{...candidate('good',3,'green'),userId:'b',name:'B'},{...candidate('fair',5,'red'),userId:'c',name:'C'},candidate('excellent',1)];const winners=drawWinners(pool,()=>0);assert.deepEqual(winners.map(w=>w.winner?.userId),['a','b','c']);assert.deepEqual(winners.map(w=>w.amountCents),[100000,50000,20000]);assert.equal(drawWinners([],()=>0).every(w=>w.winner===null),true)});
test('Drawing rejects biased random values before selecting an index',()=>{const values=[4294967295,4];assert.equal(unbiasedIndex(3,()=>values.shift()!),1);assert.throws(()=>unbiasedIndex(0))});

test('Facility evaluation requires all scores and accountable evaluator details',()=>{const v={evaluatorName:'Jane Smith',evaluatorTitle:'DON',contact:'don@example.test',comments:'Good performance',sourceReference:'Review 1',rating:'good',scores:Object.fromEntries(Object.keys(evaluationCriteria).map(k=>[k,'good']))};assert.equal(validateFeedback('evaluation',v).rating,'good');assert.throws(()=>validateFeedback('evaluation',{...v,scores:{}}));assert.throws(()=>validateFeedback('evaluation',{...v,evaluatorName:'Jane'}));assert.throws(()=>validateFeedback('dnr',{...v,comments:''}));assert.throws(()=>validateFeedback('other',v))});
test('Review transitions distinguish pending allegation, confirmed DNR, lifted and erroneous history',()=>{assert.equal(permittedReview('dnr','pending','active'),true);assert.equal(permittedReview('dnr','active','resolved'),true);assert.equal(permittedReview('dnr','resolved','void'),true);assert.equal(permittedReview('dnr','dismissed','active'),false);assert.equal(permittedReview('evaluation','pending','approved'),true);assert.equal(permittedReview('evaluation','approved','active'),false);assert.equal(blocksContest('pending'),true);assert.equal(blocksContest('resolved'),true);assert.equal(blocksContest('void'),false)});
test('Only active DNR at the matching employee/facility blocks booking',()=>{const r={kind:'dnr',status:'active',userId:'a',facility:'Facility A'};assert.equal(blocksBooking(r,'a','Facility A'),true);assert.equal(blocksBooking(r,'b','Facility A'),false);assert.equal(blocksBooking(r,'a','Facility B'),false);assert.equal(blocksBooking({...r,status:'pending'},'a','Facility A'),false);assert.equal(blocksBooking({...r,status:'resolved'},'a','Facility A'),false)});
test('Poor approved facility ratings do not qualify for any contest tier',()=>{assert.equal(candidate('poor',0,'gold').eligible,false);assert.equal(candidate('poor',3,'green').eligible,false);assert.equal(candidate('poor',5,'red').eligible,false)});
test('A late evaluation approval cannot change a closed-quarter drawing pool',()=>{const r={kind:'evaluation',status:'approved',quarterKey:awardQuarter.key,reviewedAt:awardQuarter.end-1};assert.equal(reviewedInQuarter(r),true);assert.equal(reviewedInQuarter({...r,reviewedAt:awardQuarter.end}),false);assert.equal(reviewedInQuarter({...r,status:'pending'}),false)});

import {suspensionDays,suspensionSummary,validateAbsenceReport,dayMs} from '../lib/no-call-no-show.ts';
test('NCNS policy escalates 7, 14, 30 days with 30 days for subsequent incidents',()=>{assert.deepEqual([1,2,3,4,10].map(suspensionDays),[7,14,30,30,30]);assert.throws(()=>suspensionDays(0));});
test('NCNS suspension expires exactly at the end and uses the latest overlapping end',()=>{const rows=[{submitted_at:100,ends_at:100+7*dayMs,offense:1,days:7},{submitted_at:200,ends_at:200+14*dayMs,offense:2,days:14}];assert.equal(suspensionSummary(rows,200).end,200+14*dayMs);assert.equal(suspensionSummary(rows,200+14*dayMs).suspended,false);assert.equal(suspensionSummary(rows,99).suspended,false)});
test('NCNS requires explicit no-call confirmation and a named reporter',()=>{const report={evaluatorName:'Facility Supervisor',evaluatorTitle:'Director',details:'No arrival or contact received.',noCallConfirmed:true};assert.equal(validateAbsenceReport(report).noCallConfirmed,true);assert.throws(()=>validateAbsenceReport({...report,noCallConfirmed:false}));assert.throws(()=>validateAbsenceReport({...report,evaluatorName:'Supervisor'}));assert.throws(()=>validateAbsenceReport({...report,details:''}));});

import {rewardExclusion,rewardYear} from '../lib/no-call-no-show.ts';
test('NCNS rewards exclusion starts at infraction, lasts after suspension, and ends January 1 Eastern',()=>{const at=Date.parse('2026-03-20T07:00:00-04:00'),incidents=[{id:'ncns',user_id:'nurse',infraction_at:at}],end=Date.parse('2027-01-01T00:00:00-05:00');assert.equal(rewardExclusion(incidents,'nurse',{start:at,end:at+1},at)?.end,end);assert.ok(rewardExclusion(incidents,'nurse',{start:end-1,end},end-1));assert.equal(rewardExclusion(incidents,'nurse',{start:end,end:end+1},end),null);assert.ok(rewardExclusion(incidents,'nurse',{start:at+100*dayMs,end:at+101*dayMs},at+100*dayMs));assert.equal(rewardExclusion(incidents,'other',{start:at,end:at+1},at),null)});
test('NCNS exclusion preserves earlier awards and uses the Eastern infraction year for delayed reports',()=>{const at=Date.parse('2027-01-01T04:59:59Z'),incidents=[{id:'ncns',user_id:'a',infraction_at:at}];assert.equal(rewardYear(at).year,2026);assert.equal(rewardYear(at+1000).year,2027);assert.equal(rewardExclusion(incidents,'a',{start:at-dayMs,end:at},at+1000),null);assert.ok(rewardExclusion(incidents,'a',{start:at-dayMs,end:at+1},at+1000));assert.equal(rewardExclusion(incidents,'a',{start:at+1000,end:at+2000},at+2000),null);assert.equal(rewardExclusion([],'a',{start:at-dayMs,end:at+1},at+1000),null)});
test('NCNS exclusion removes a fully qualified contest candidate and their icon from the drawing',()=>{const q=contestQuarter(Date.parse('2026-05-01T12:00:00Z')),now=q.end-1,start=q.start+dayMs,end=start+8*3600000,shift={assignmentId:'one',userId:'a',name:'Nurse',facility:'Hospital',start,end,state:'accepted',status:'filled',updatedAt:start,clockIn:start,clockOut:end};const review={userId:'a',quarterKey:q.key,facility:'Hospital',rating:'excellent'},nomination={userId:'a',quarterKey:q.key,category:'gold' as const,clearance:'clear'};assert.equal(contestCandidate('a','Nurse',q,[shift],[review],nomination,false,now).eligible,true);const exclusion=rewardExclusion([{id:'absence',user_id:'a',infraction_at:start+dayMs}],'a',q,now);const c=contestCandidate('a','Nurse',q,[shift],[review],nomination,false,now,exclusion);assert.equal(c.eligible,false);assert.equal(c.category,null);assert.match(c.reasons[0],/December 31, 2026/);assert.equal(drawWinners([c])[0].winner,null)});

import {inactiveStatus,payrollDocument,basicEmployeeProfile,validateEmployment} from '../lib/employment.ts';
test('Inactive employment permits only payroll kinds and limits demographic data',()=>{assert.equal(inactiveStatus('quit'),true);assert.equal(inactiveStatus('terminated'),true);assert.equal(inactiveStatus('active'),false);assert.equal(payrollDocument('paystub'),true);assert.equal(payrollDocument('w2'),true);assert.equal(payrollDocument('license'),false);const p=basicEmployeeProfile({firstName:'Nurse',phone:'555',licenseNumber:'secret',referenceName:'private',duties:'private',startDate:'prior employer date'},'nurse@example.test');assert.deepEqual(p,{email:'nurse@example.test',firstName:'Nurse',phone:'555'});});
test('Employment status validates real calendar dates and separates employment from application history',()=>{const x={status:'quit',startDate:'2026-01-01',endDate:'2026-09-30',note:'Resignation recorded'};assert.equal(validateEmployment(x).endDate,'2026-09-30');assert.throws(()=>validateEmployment({...x,endDate:'2026-02-30'}));assert.throws(()=>validateEmployment({...x,endDate:'2025-12-31'}));assert.throws(()=>validateEmployment({...x,status:'unknown'}));assert.throws(()=>validateEmployment({...x,note:''}));assert.equal(validateEmployment({...x,status:'active'}).endDate,null)});

import {publicMerchUrl,validateMerchConnection} from '../lib/merch.ts';
test('Merch connection supports Squarespace and custom domains with safe public URLs',()=>{assert.equal(publicMerchUrl('https://alwaysnursing.squarespace.com/merch'),'https://alwaysnursing.squarespace.com/merch');assert.equal(publicMerchUrl(' https://alwaysnursing.com/shop?category=uniforms '),'https://alwaysnursing.com/shop?category=uniforms');for(const value of ['javascript:alert(1)','http://alwaysnursing.com/merch','//alwaysnursing.com/merch','https://localhost/shop','https://127.0.0.1/shop','https://user:pass@alwaysnursing.com/shop','https://account.squarespace.com/','https://alwaysnursing.squarespace.com/config'])assert.throws(()=>publicMerchUrl(value));assert.throws(()=>validateMerchConnection({enabled:true,url:''}));assert.deepEqual(validateMerchConnection({enabled:false,url:''}),{enabled:false,url:''})});

test('Annual credential dates must be verified, recent, and valid through the shift',()=>{assert.equal(eligibility({...verified,issuedDates:undefined},shift,now).length,3);assert(eligibility({...verified,issuedDates:{...verified.issuedDates!,tb:'2020-01-01'}},shift,now).some(x=>x.includes('TB')));assert(eligibility({...verified,issuedDates:{...verified.issuedDates!,bls:'2099-01-01'}},shift,now).some(x=>x.includes('BLS')))});

test('Shift board distinguishes reopened, booked, urgent and facility-canceled shifts',async()=>{const {shiftPresentation}=await import('../lib/workflow.ts');assert.equal(shiftPresentation('open',{urgentCents:0}).label,'Available');assert.equal(shiftPresentation('filled',{urgent:true}).label,'Booked');assert.equal(shiftPresentation('open',{urgent:true}).label,'Urgent · Available');assert.equal(shiftPresentation('cancelled',{urgent:true}).label,'Facility Canceled');});

test('New theme song replaces previous defaults and later agency removal remains respected',async()=>{const {defaultHome,resolveHome,validateHome,themeSong}=await import('../lib/home.ts');assert.equal(resolveHome({...defaultHome,song:'',autoplay:false,songRevision:undefined}).song,themeSong);assert.equal(resolveHome({...defaultHome,songRevision:undefined}).autoplay,true);const removed=validateHome({...defaultHome,song:'',autoplay:false});assert.equal(resolveHome(removed).song,'');assert.equal(resolveHome(removed).autoplay,false);});

test('Weekly summary uses Eastern Sunday boundaries, splits overnight hours and clips breaks',async()=>{const {summaryWeek,weeklyRows}=await import('../lib/weekly-summary.ts');const w=summaryWeek('2026-10-04');assert.equal(new Date(w.start).toISOString(),'2026-10-04T04:00:00.000Z');const shift={facility:'Meadow Care Center',baseCents:3000,differentialCents:500,urgentCents:2500,urgentUnit:'shift'} as any,time={in:{at:Date.parse('2026-10-04T02:00:00Z')},out:{at:Date.parse('2026-10-04T08:00:00Z')},breaks:[{start:Date.parse('2026-10-04T03:30:00Z'),end:Date.parse('2026-10-04T04:30:00Z')}]} as any;const rows=weeklyRows([{id:'shift',shift,time}],w);assert.equal(rows[0].hours,3.5);assert.equal(rows[0].payCents,14750);assert.equal(rows[0].initials,'MCC');const prior=weeklyRows([{id:'shift',shift,time}],summaryWeek('2026-10-03'));assert.equal(prior[0].hours,1.5);assert.equal(prior[0].bonusCents,0);assert.equal(weeklyRows([{id:'pending',shift,time:{...time,out:undefined}}],w).length,0);const dst=summaryWeek('2026-11-01');assert.equal((dst.end-dst.start)/3600000,169);});

test('Supervisor title must be RN or LPN for new attendance signoffs',async()=>{const {validateSupervisorTitle}=await import('../lib/workflow.ts');assert.equal(validateSupervisorTitle('RN'),'RN');assert.equal(validateSupervisorTitle('LPN'),'LPN');for(const value of [undefined,'','CNA','Manager'])assert.throws(()=>validateSupervisorTitle(value),/RN or LPN/);});

test('Referral bonuses require five distinct completed shifts and award milestones once',async()=>{const {referralRewards}=await import('../lib/referrals.ts');const claims=Array.from({length:20},(_,i)=>({id:'r'+i,referrerId:'referrer',workerId:'worker'+i,name:'Test Worker',title:'RN',status:'approved',createdAt:0})),times=claims.flatMap((r,i)=>Array.from({length:5},(_,j)=>({userId:r.workerId,shiftId:i+'-'+j,clockIn:1,clockOut:100+i*10+j})));const result=referralRewards(claims,[...times,times[0]],[],[],1000);assert.equal(result.referrals[0].completed,5);assert.equal(result.rewards.filter(r=>r.referralId).length,20);assert.equal(result.rewards.find(r=>r.threshold===10)?.amountCents,50000);assert.equal(result.rewards.find(r=>r.threshold===20)?.amountCents,100000);assert.equal(result.rewards.reduce((n,r)=>n+r.amountCents,0),450000);assert.equal(referralRewards(claims.slice(0,1),times.slice(0,4),[],[],1000).rewards.length,0);assert.equal(referralRewards([{...claims[0],status:'pending'}],times,[],[],1000).rewards.length,0);const excluded=referralRewards(claims.slice(0,1),times,[],[{id:'ncns',user_id:'referrer',infraction_at:50}],1000);assert.ok(excluded.rewards[0].excluded);});
