export type HomeConfig={songRevision?:string;picture:string;caption:string;position:number;song:string;autoplay:boolean;video:string};
export const themeSong='/always-nursing-theme.mp3';
export const songRevision='always-nursing-remix-2026-10-04';
export function resolveHome(config?:HomeConfig):HomeConfig{return !config?defaultHome:config.songRevision===songRevision?config:{...config,song:themeSong,autoplay:true,songRevision};}
export const defaultHome:HomeConfig={picture:'',caption:'Always Nursing — Care That Counts, Careers That Matter',position:50,song:themeSong,autoplay:true,songRevision,video:''};
export type HomePreferences={sms:boolean;phone:string;source:string;referrer:string;other:string};
export const defaultPreferences:HomePreferences={sms:false,phone:'',source:'',referrer:'',other:''};
export const referralSources=['Referred','Google','YouTube','Facebook','Instagram','Website','Other'];
export const smsDisclosure='I agree to receive recruiting, scheduling, and employment text messages from Always Nursing at the number I provide. Consent is optional and is not a condition of employment. Message frequency varies. Message and data rates may apply. Reply STOP to opt out or HELP for help. I can also withdraw consent here.';
export function videoEmbed(value:string){if(!value)return '';const u=new URL(value);if(u.protocol!=='https:')throw new Error('Use an HTTPS YouTube or Vimeo link');const host=u.hostname.toLowerCase();let id='';if(['youtube.com','www.youtube.com','m.youtube.com'].includes(host)){id=u.searchParams.get('v')||u.pathname.match(/^\/(?:embed|shorts)\/([\w-]+)$/)?.[1]||''}else if(host==='youtu.be')id=u.pathname.slice(1);if(id&&/^[\w-]{11}$/.test(id))return 'https://www.youtube-nocookie.com/embed/'+id;if(['vimeo.com','www.vimeo.com','player.vimeo.com'].includes(host)){const match=u.pathname.match(/^\/(?:video\/)?(\d+)$/);if(match)return 'https://player.vimeo.com/video/'+match[1]}throw new Error('Enter a YouTube video or Vimeo video link');}
export function validateHome(x:any):HomeConfig{if(!x||typeof x.caption!=='string'||x.caption.length>300||!Number.isFinite(x.position)||x.position<0||x.position>100||typeof x.autoplay!=='boolean'||typeof x.video!=='string'||x.video.length>500)throw new Error('Check Home page settings');for(const k of ['picture','song'])if(typeof x[k]!=='string'||(x[k]&&!(k==='song'&&x[k]===themeSong)&&!/^\/api\/home-media\/[a-f0-9-]{36}$/.test(x[k])))throw new Error('Upload Home media through the agency controls');videoEmbed(x.video);return {songRevision,picture:x.picture,caption:x.caption,position:x.position,song:x.song,autoplay:x.autoplay,video:x.video};}
export function validatePreferences(x:any):HomePreferences{if(!x||typeof x.sms!=='boolean')throw new Error('Choose SMS consent');for(const k of ['phone','source','referrer','other'])if(typeof x[k]!=='string'||x[k].length>300)throw new Error('Check your contact preferences');if(x.sms&&!/^\+?[\d\s().-]{7,30}$/.test(x.phone))throw new Error('Enter a valid mobile number for SMS consent');if(x.source&&!referralSources.includes(x.source))throw new Error('Choose how you heard about us');if(x.source==='Referred'&&!x.referrer.trim())throw new Error('Enter the referring person’s name');if(x.source==='Other'&&!x.other.trim())throw new Error('Tell us how you heard about us');return {sms:x.sms,phone:x.phone.trim(),source:x.source,referrer:x.source==='Referred'?x.referrer.trim():'',other:x.source==='Other'?x.other.trim():''};}
