export const INCENTIVE_ZONE='America/New_York';
const DAY=86400000;
const calendarFormat=new Intl.DateTimeFormat('en-US',{timeZone:INCENTIVE_ZONE,year:'numeric',month:'2-digit',day:'2-digit'});
const timestampFormat=new Intl.DateTimeFormat('en-US',{timeZone:INCENTIVE_ZONE,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'});
const periodCache=new Map<string,IncentivePeriod>();
export type IncentivePeriod={key:string;start:number;end:number;days:number};
function midnight(utcDate:number){let target=utcDate;for(let i=0;i<3;i++){const parts=timestampFormat.formatToParts(target);const values=Object.fromEntries(parts.map(p=>[p.type,p.value]));const represented=Date.UTC(+values.year,+values.month-1,+values.day,+values.hour,+values.minute,+values.second);target+=utcDate-represented}return target}
export function incentivePeriod(at:number):IncentivePeriod{const parts=calendarFormat.formatToParts(at),v=Object.fromEntries(parts.map(p=>[p.type,p.value]));const year=+v.year,jan=Date.UTC(year,0,1),today=Date.UTC(year,+v.month-1,+v.day),index=Math.floor((today-jan)/DAY/14),startDate=jan+index*14*DAY,endDate=Math.min(startDate+14*DAY,Date.UTC(year+1,0,1));const key=`${year}-${String(index+1).padStart(2,'0')}`;const cached=periodCache.get(key);if(cached)return cached;const period={key,start:midnight(startDate),end:midnight(endDate),days:(endDate-startDate)/DAY};if(periodCache.size>1000)periodCache.clear();periodCache.set(key,period);return period}
export type IncentiveShift={assignmentId:string;userId:string;name:string;facility:string;start:number;end:number;state:string;status:string;updatedAt:number;clockIn?:number;clockOut?:number};
export function countedShift(s:IncentiveShift){return s.status!=='cancelled'&&s.state!=='facility_cancelled'&&(s.state==='accepted'||(s.state==='employee_cancelled'&&s.updatedAt>=s.start))}
export function evaluateIncentive(period:IncentivePeriod,all:IncentiveShift[],now:number){const shifts=all.filter(s=>countedShift(s)&&incentivePeriod(s.start).key===period.key);let earnedChecks=0;const details=shifts.map(s=>{const inGood=Number.isFinite(s.clockIn)&&Math.floor(s.clockIn!/60000)<=Math.floor(s.start/60000)&&s.clockIn!>=s.start-3600000;const outGood=Number.isFinite(s.clockOut)&&Math.floor(s.clockOut!/60000)===Math.floor(s.end/60000)&&!!s.clockIn&&s.clockOut!>=s.clockIn!&&s.clockOut!>=s.end;if(inGood)earnedChecks++;if(outGood)earnedChecks++;return {...s,inGood,outGood}});const closed=now>=period.end&&shifts.every(s=>now>=s.end);const failed=details.some(s=>(s.clockIn!==undefined&&!s.inGood)||(s.clockOut!==undefined&&!s.outGood)||(now>s.start+60000&&!s.clockIn)||(now>s.end+60000&&!s.clockOut)||s.state!=='accepted');const eligible=closed&&period.days===14&&shifts.length>0&&!failed&&earnedChecks===shifts.length*2;return {period,details,totalChecks:shifts.length*2,earnedChecks,progress:shifts.length?Math.round(earnedChecks/(shifts.length*2)*100):0,closed,failed,eligible,amountCents:eligible?2500:0}}
