export type ApplicationData=Record<string,string>;
export type ApplicationField={key:string;label:string;type?:string;options?:string[]};
const f=(key:string,label:string,type='text',options?:string[]):ApplicationField=>({key,label,type,options});
export const contactFields=[f('firstName','Legal First Name'),f('lastName','Legal Last Name'),f('preferredName','Preferred Name'),f('email','Email','email'),f('phone','Mobile Phone','tel'),f('alternatePhone','Alternate Phone','tel'),f('address','Street Address'),f('cityStateZip','City, State & ZIP'),f('role','Position / License Type','select',['RN','LPN','CNA','Other']),f('emergencyContact','Emergency Contact Name & Relationship'),f('emergencyPhone','Emergency Contact Phone','tel')];
export const employmentFields=[f('availability','Days / Hours Available'),f('preferredShifts','Preferred Shifts'),f('employmentType','Employment Preference','select',['Per Diem','Part Time','Full Time','Travel / Contract']),f('availableStart','Available Start Date','date'),f('authorizedToWork','Authorized To Work In The United States?','select',['Yes','No']),f('requiresSponsorship','Will You Require Employment Sponsorship?','select',['Yes','No']),f('travelRadius','Travel Radius / Preferred Locations'),f('previousAgencyEmployment','Previously Worked For Always Nursing?','select',['Yes','No']),f('previousAgencyDates','Previous Always Nursing Dates'),f('noEmploymentHistory','No Prior Employment History','select',['Yes','No'])];
export function jobFields(i:number){const key=(name:string)=>i===1?({employer:'employer',title:'jobTitle',start:'startDate',end:'endDate',duties:'duties'} as Record<string,string>)[name]||'job1_'+name:'job'+i+'_'+name;return [f(key('employer'),'Employer / Facility'),f(key('title'),'Position / Job Title'),f(key('address'),'Employer Address'),f(key('phone'),'Employer Phone','tel'),f(key('supervisor'),'Supervisor Name & Title'),f(key('start'),'Start Month','month'),f(key('end'),'End Month','month'),f(key('current'),'Currently Employed?','select',['Yes','No']),f(key('duration'),'Total Time Worked (Years / Months)'),f(key('hours'),'Average Hours Per Week'),f(key('duties'),'Responsibilities, Units & Clinical Setting','textarea'),f(key('reason'),'Reason For Leaving'),f(key('contact'),'May We Contact This Employer?','select',['Yes','No'])]}
export function referenceFields(i:number){const k=(name:string)=>i===1?({name:'referenceName',relationship:'referenceRelationship',email:'referenceEmail',phone:'referencePhone'} as Record<string,string>)[name]||'reference1_'+name:'reference'+i+'_'+name;return [f(k('name'),'Professional Reference Full Name'),f(k('relationship'),'Title / Professional Relationship'),f(k('employer'),'Organization'),f(k('email'),'Email','email'),f(k('phone'),'Phone','tel'),f(k('known'),'Length Of Time Known'),f(k('contact'),'May We Contact This Reference?','select',['Yes','No'])]}
export function schoolFields(prefix:string,high=false){return [f(prefix+'_name',high?'High School Name':'Trade / Vocational School Or College'),f(prefix+'_location','City / State'),f(prefix+'_start','From','month'),f(prefix+'_end','To','month'),f(prefix+'_duration','Time Attended'),f(prefix+'_program',high?'Diploma / GED / Other':'Program / Major'),f(prefix+'_award',high?'Diploma / GED Earned?':'Degree / Certificate Earned'),f(prefix+'_graduated','Completed / Graduated?','select',['Yes','No','In Progress'])]}
export const licenseFields=[f('licenseState','License State'),f('licenseType','License Type'),f('licenseNumber','License Number'),f('expirationDate','License Expiration Date','date'),f('compactLicense','Multistate / Compact License?','select',['Yes','No']),f('compactHomeState','Primary State Of Residence'),f('additionalLicenses','Other Licenses / States / Numbers','textarea')];
export const skills=[{key:'iv',label:'Are You IV Certified?'},{key:'phlebotomy',label:'Are You Certified In Phlebotomy?'},{key:'trachVent',label:'Are You Experienced With Trachs And Vents?'},{key:'woundCare',label:'Are You Experienced With Wound Care?'}];
export const ehrSystems=['PCC','Matrix','Meditech Expanse','Cerner PowerChart','WellSky','Axxess','CareVoyant','IntelliCure','WoundZoom','Tynet EHR','Epic','WeInfuse'];
export const ehrKey=(name:string)=>'ehr_'+name.replace(/[^a-zA-Z]/g,'');
export const credentialTabs=[{kind:'tb',label:'TB',date:'tbDate',dateLabel:'TB Test Date'},{kind:'license',label:'License',date:'expirationDate',dateLabel:'License Expiration Date'},{kind:'bls',label:'BLS / CPR',date:'blsDate',dateLabel:'BLS / CPR Completed Date'},{kind:'physical',label:'Physical',date:'physicalDate',dateLabel:'Physical Date'},{kind:'specialty',label:'Specialty-Specific',date:'specialtyExpiry',dateLabel:'Specialty Credential Expiration Date'}];
export const extraFields=[f('education','Additional Education / Training','textarea'),f('specialtyName','Specialty Credential Name'),f('specialtyApplicable','Specialty Credentials Applicable?','select',['Yes','No']),f('specialtyIssuer','Specialty Credential Issuer'),f('specialtyExpiry','Specialty Expiration','date'),f('tbDate','TB Test Date','date'),f('blsDate','BLS / CPR Completed Date','date'),f('blsExpiry','BLS / CPR Card Expiration','date'),f('physicalDate','Physical Date','date'),f('applicationMode','Application Mode'),f('attested','Applicant Certification'),f('applicantSignature','Applicant Printed Full Name'),f('signatureDate','Certification Date','date')];
const allowed=new Set([...contactFields,...employmentFields,...[1,2,3].flatMap(jobFields),...[1,2,3].flatMap(referenceFields),...schoolFields('highSchool',true),...['school1','school2','school3'].flatMap(p=>schoolFields(p)),...licenseFields,...extraFields].map(x=>x.key).concat(skills.flatMap(s=>[s.key+'_answer',s.key+'_duration',s.key+'_level']),ehrSystems.map(ehrKey),[1,2,3].map(i=>'job'+i+'_notApplicable'),['highSchool','school1','school2','school3'].map(p=>p+'_notApplicable')));
export function validateApplication(input:unknown):ApplicationData{if(!input||typeof input!=='object'||Array.isArray(input))throw new Error('Invalid application');const result:ApplicationData={};for(const [key,value] of Object.entries(input)){if(!allowed.has(key))continue;if(typeof value!=='string'||value.length>2000)throw new Error('Invalid '+key);result[key]=value.trim()}if(JSON.stringify(result).length>60000)throw new Error('Application is too large');return result}
export function annualExpiry(date:string){if(!/^\d{4}-\d{2}-\d{2}$/.test(date))return NaN;const [y,m,d]=date.split('-').map(Number);const original=new Date(Date.UTC(y,m-1,d));if(original.toISOString().slice(0,10)!==date)return NaN;const last=new Date(Date.UTC(y+1,m,0)).getUTCDate();return Date.UTC(y+1,m-1,Math.min(d,last),23,59,59,999)}
export function credentialDateStatus(kind:string,date:string,now=Date.now()){if(!date)return 'Date Required';const at=Date.parse(date+'T23:59:59Z');if(!Number.isFinite(at))return 'Invalid Date';if(kind==='license'||kind==='specialty')return at>=now?'Current Date — Pending Office Verification':'Expired';if(Date.parse(date+'T00:00:00Z')>now)return 'Future Date — Not Valid';return annualExpiry(date)>=now?'Within The Last Year — Pending Office Verification':'Older Than One Year — Update Required'}
export const onboardingSections=['Contact & Application','Work History','Education','Professional References','License Information','Credential Documents','Clinical Skills & EHR'];
export function sectionCompletion(data:ApplicationData,documentKinds:string[],now=Date.now()){const kinds=new Set(documentKinds),resume=data.applicationMode==='resume'&&kinds.has('resume');const result=onboardingSections.map(name=>({name,missing:[] as string[],coveredByResume:resume&&['Work History','Education','Professional References'].includes(name)}));
const add=(index:number,text:string)=>result[index].missing.push(text);
const requireFields=(index:number,fields:ApplicationField[],skip:string[]=[])=>{for(const field of fields){if(skip.includes(field.key))continue;const value=data[field.key];if(!value)add(index,field.label);else if(field.options&&!field.options.includes(value))add(index,field.label+' — Select A Valid Answer');else if(field.type==='email'&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value))add(index,field.label+' — Enter A Valid Email');else if(field.type==='date'&&(!/^\d{4}-\d{2}-\d{2}$/.test(value)||!Number.isFinite(annualExpiry(value))))add(index,field.label+' — Enter A Valid Date');else if(field.type==='month'&&!/^\d{4}-(0[1-9]|1[0-2])$/.test(value))add(index,field.label+' — Enter A Valid Month')}};
requireFields(0,contactFields,['preferredName','alternatePhone']);requireFields(0,employmentFields,data.previousAgencyEmployment==='Yes'?[]:['previousAgencyDates']);if(data.applicationMode==='resume'&&!kinds.has('resume'))add(0,'Upload A Résumé PDF');
if(!resume){for(let i=1;i<=3;i++){if(data.noEmploymentHistory==='Yes'||data['job'+i+'_notApplicable']==='yes')continue;const fields=jobFields(i),current=fields.find(f=>f.label==='Currently Employed?')!;const skip=data[current.key]==='Yes'?fields.filter(f=>['End Month','Reason For Leaving'].includes(f.label)).map(f=>f.key):[];requireFields(1,fields,skip)}for(const prefix of ['highSchool','school1','school2','school3'])if(data[prefix+'_notApplicable']!=='yes')requireFields(2,schoolFields(prefix,prefix==='highSchool'));for(let i=1;i<=3;i++){const fields=referenceFields(i);requireFields(3,fields,[fields[3].key,fields[4].key]);if(!data[fields[3].key]&&!data[fields[4].key])add(3,'Professional Reference '+i+' — Email Or Phone Required');if(data[fields[3].key]&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(data[fields[3].key]))add(3,'Professional Reference '+i+' — Valid Email Required')}}
requireFields(4,licenseFields,['additionalLicenses',...(data.compactLicense==='Yes'?[]:['compactHomeState'])]);if(!credentialDateStatus('license',data.expirationDate||'',now).includes('Pending Office Verification'))add(4,'Current License Expiration Date');
for(const c of credentialTabs){if(c.kind==='specialty')continue;if(!kinds.has(c.kind))add(5,c.label+' Document Required');if(!credentialDateStatus(c.kind,data[c.date]||'',now).includes('Pending Office Verification'))add(5,c.label+' — '+credentialDateStatus(c.kind,data[c.date]||'',now))}
if(!data.blsExpiry||!credentialDateStatus('license',data.blsExpiry,now).includes('Pending Office Verification'))add(5,'Current BLS / CPR Card Expiration Date');
if(!['Yes','No'].includes(data.specialtyApplicable||''))add(5,'Specialty-Specific — Select Applicable Yes Or No');else if(data.specialtyApplicable==='Yes'){requireFields(5,[{key:'specialtyName',label:'Specialty Credential Name'},{key:'specialtyIssuer',label:'Specialty Credential Issuer'}]);if(!kinds.has('specialty'))add(5,'Specialty Credential Document Required');if(data.specialtyExpiry&&!credentialDateStatus('specialty',data.specialtyExpiry,now).includes('Pending Office Verification'))add(5,'Current Specialty Credential Expiration Date')}
for(const skill of skills){const answer=data[skill.key+'_answer'];if(!['Yes','No'].includes(answer||''))add(6,skill.label+' — Select Yes Or No');if(answer==='Yes'){if(!data[skill.key+'_duration'])add(6,skill.label+' — Duration Required');if(!['Less Than One Year','1–5 Years','5 And Over Years'].includes(data[skill.key+'_level']||''))add(6,skill.label+' — Experience Level Required')}}for(const name of ehrSystems)if(!['Yes','No'].includes(data[ehrKey(name)]||''))add(6,name+' — Select Yes Or No');return result}
export function submissionErrors(data:ApplicationData,documents:boolean|string[],now=Date.now()){const kinds=Array.isArray(documents)?documents:documents?['resume']:[];const sections=sectionCompletion(data,kinds,now),errors=sections.filter(s=>s.missing.length).map(s=>s.name+': '+s.missing.join(', '));if(data.attested!=='yes'||!data.applicantSignature?.trim().includes(' ')||!data.signatureDate||!Number.isFinite(annualExpiry(data.signatureDate))||Date.parse(data.signatureDate+'T00:00:00Z')>now)errors.push('Applicant Certification: Full Name, Valid Date And Acknowledgement Are Required');return errors}
