import {countedShift,type IncentiveShift} from './incentives.ts';
export const contestTiers={gold:{label:'Golden Star Award',icon:'⭐',amountCents:100000,rating:'excellent',minLate:0,maxLate:0},green:{label:'Green Heart Award',icon:'💚',amountCents:50000,rating:'good',minLate:3,maxLate:5},red:{label:'Red Apple Award',icon:'🍎',amountCents:20000,rating:'fair',minLate:5,maxLate:8}} as const;
export type Tier=keyof typeof contestTiers;
export type Quarter={key:string;start:number;end:number;rosterAt:number};
const dateFormat=new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',year:'numeric',month:'numeric'});
const timestampFormat=new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',year:'numeric',month:'numeric',day:'numeric',hour:'numeric',minute:'numeric',second:'numeric',hourCycle:'h23'});
function easternMidnight(day:number){let at=day;for(let i=0;i<3;i++){const v=Object.fromEntries(timestampFormat.formatToParts(at).map(p=>[p.type,p.value]));at+=day-Date.UTC(+v.year,+v.month-1,+v.day,+v.hour,+v.minute,+v.second)}return at}
const cache=new Map<string,Quarter>();
export function contestQuarter(at:number):Quarter{const v=Object.fromEntries(dateFormat.formatToParts(at).map(p=>[p.type,p.value])),year=+v.year,q=Math.floor((+v.month-1)/3),key=`${year}-Q${q+1}`;const existing=cache.get(key);if(existing)return existing;const endDay=Date.UTC(year,(q+1)*3,1),result={key,start:easternMidnight(Date.UTC(year,q*3,1)),end:easternMidnight(endDay),rosterAt:easternMidnight(endDay-7*86400000)};if(cache.size>500)cache.clear();cache.set(key,result);return result}
export type Evaluation={userId:string;quarterKey:string;facility:string;rating:string;reference?:string};
export type Nomination={userId:string;quarterKey:string;category:Tier;clearance:string};
export function contestCandidate(userId:string,name:string,q:Quarter,shifts:IncentiveShift[],reviews:Evaluation[],nomination:Nomination|undefined,hasDnr:boolean,now:number,exclusion:{reason:string;start:number;end:number}|null=null){const worked=shifts.filter(s=>s.userId===userId&&countedShift(s)&&contestQuarter(s.start).key===q.key&&s.start<=now);let late=0,missing=0,earlyOut=0;for(const s of worked){const inLate=s.clockIn!==undefined&&Math.floor(s.clockIn/60000)>Math.floor(s.start/60000),outLate=s.clockOut!==undefined&&Math.floor(s.clockOut/60000)>Math.floor(s.end/60000);if(inLate||outLate)late++;if((now>s.start+60000&&!s.clockIn)||(now>s.end+60000&&!s.clockOut))missing++;if(s.clockOut!==undefined&&s.clockOut<s.end)earlyOut++}const facilities=[...new Set(worked.filter(s=>s.clockIn!==undefined).map(s=>s.facility))];const ratings=reviews.filter(r=>r.userId===userId&&r.quarterKey===q.key&&facilities.includes(r.facility));const missingReviews=facilities.filter(f=>!ratings.some(r=>r.facility===f));const rating=ratings.some(r=>r.rating==='poor')?'poor':ratings.some(r=>r.rating==='fair')?'fair':ratings.some(r=>r.rating==='good')?'good':ratings.length?'excellent':null;const category=exclusion?null:nomination?.category||null,tier=category?contestTiers[category]:null;const reasons:string[]=[];if(exclusion)reasons.push(exclusion.reason);if(!worked.length||!facilities.length)reasons.push('A worked facility shift is required');if(missing)reasons.push(`${missing} shift(s) with missing attendance`);if(earlyOut)reasons.push('Early clock-out recorded');if(missingReviews.length)reasons.push('Facility evaluations still needed');if(!rating)reasons.push('Facility evaluation not recorded');if(!nomination)reasons.push('Agency award checkmark not recorded');if(nomination?.clearance!=='clear')reasons.push('Agency must confirm no DNR');if(hasDnr)reasons.push('A DNR has been recorded');if(tier&&(tier.rating!==rating||late<tier.minLate||late>tier.maxLate))reasons.push('Evaluation / late-shift count does not match selected award');return {userId,name,category,exclusion,eligible:reasons.length===0,late,missing,earlyOut,rating,facilities,missingReviews,reasons}}
export function unbiasedIndex(length:number,random:()=>number=()=>crypto.getRandomValues(new Uint32Array(1))[0]){if(!Number.isInteger(length)||length<1||length>4294967296)throw new Error('Invalid candidate count');const limit=Math.floor(4294967296/length)*length;let value:number;do{value=random()}while(value>=limit);return value%length}
export function drawWinners(candidates:ReturnType<typeof contestCandidate>[],random?:()=>number){return (Object.keys(contestTiers) as Tier[]).map(category=>{const eligible=candidates.filter(c=>c.eligible&&c.category===category);const c=eligible.length?eligible[unbiasedIndex(eligible.length,random)]:null;return {category,...contestTiers[category],winner:c?{userId:c.userId,name:c.name}:null,candidateCount:eligible.length}})}
