import {annualExpiry} from "./onboarding.ts";
export type Shift={urgent?:boolean;facility:string;address:string;facilityType?:string;facilityPhone?:string;shiftPeriod?:string;notes?:Record<string,string>;state:string;role:string;start:number;end:number;timeZone:string;baseCents:number;differentialCents:number;urgentCents:number;urgentUnit:"hour"|"shift";lat:number;lon:number;radius:number;requirements:string[];source:string};
export type Compliance={role:string;states:string[];expires:Record<string,number>;sourceNote:string;issuedDates?:Record<string,string>};
export type Stroke=[number,number][];
export type Signoff={supervisorTitle?:"RN"|"LPN";employeeName:string;supervisorName:string;signature:Stroke[];at:number;location?:{lat:number;lon:number;accuracy:number;at:number}};
export type TimeRecord={in:Signoff;out?:Signoff;breaks:{start:number;end?:number}[];noBreak?:boolean};
export const coreRequirements=["license","bls","tb","physical"];
export function eligibility(c:Compliance|null,s:Shift,now:number){const errors:string[]=[];if(!c)return ["Office credential verification is required"];if(c.role!==s.role)errors.push(`${s.role} qualification required`);if(!c.states.includes(s.state))errors.push(`Verified ${s.state} license authorization required`);for(const k of ['tb','bls','physical']){const date=c.issuedDates?.[k]||'',expiry=annualExpiry(date);if(!Number.isFinite(expiry)||expiry<Math.max(now,s.end)||Date.parse(date+'T00:00:00Z')>now)errors.push(k.toUpperCase()+' needs an office-verified completion date within the last year through the shift')}for(const k of new Set([...coreRequirements,...s.requirements])){if(!Number.isFinite(c.expires[k])||c.expires[k]<Math.max(now,s.end))errors.push(`${k.toUpperCase()} must be verified and current through the shift`)}return errors}
export function distanceMeters(a:number,b:number,c:number,d:number){const rad=Math.PI/180,x=Math.sin((c-a)*rad/2)**2+Math.cos(a*rad)*Math.cos(c*rad)*Math.sin((d-b)*rad/2)**2;return 6371000*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
export function validateLocation(location:Signoff["location"],s:Shift,now:number){if(!location||![location.lat,location.lon,location.accuracy,location.at].every(Number.isFinite)||Math.abs(location.lat)>90||Math.abs(location.lon)>180||location.accuracy<=0)throw new Error("A valid location reading is required");if(Math.abs(now-location.at)>60000)throw new Error("Refresh your location; the reading is older than one minute");if(location.accuracy>Math.min(s.radius,100))throw new Error("Location accuracy is too low; obtain a clearer GPS reading");const distance=distanceMeters(location.lat,location.lon,s.lat,s.lon);if(distance+location.accuracy>s.radius)throw new Error("You must be within the facility check-in boundary");return distance}
export function validSignature(value:unknown):value is Stroke[]{if(!Array.isArray(value)||value.length<1||value.length>100)return false;let points=0;for(const stroke of value){if(!Array.isArray(stroke)||stroke.length<2)return false;points+=stroke.length;for(const p of stroke)if(!Array.isArray(p)||p.length!==2||p.some(v=>typeof v!=="number"||!Number.isFinite(v)||v<0||v>1))return false}return points>=3&&points<=4000}
export function applyTimeAction(record:TimeRecord|null,action:string,now:number,signoff?:Signoff,noBreak?:boolean){if(action==="clockIn"){if(record)throw new Error("This assignment already has a clock-in record");if(!signoff)throw new Error("Supervisor signoff is required");return {in:signoff,breaks:[]} as TimeRecord}if(!record||record.out)throw new Error("A currently clocked-in assignment is required");const copy=structuredClone(record);const open=copy.breaks.find(b=>!b.end);if(action==="breakStart"){if(open)throw new Error("A break is already active");copy.breaks.push({start:now})}else if(action==="breakEnd"){if(!open)throw new Error("No break is active");open.end=now}else if(action==="clockOut"){if(open)throw new Error("End the active break before clocking out");if(!signoff)throw new Error("Supervisor signoff is required");if(copy.breaks.length===0&&noBreak!==true)throw new Error("Confirm no break taken before supervisor sign-out");if(copy.breaks.length>0&&noBreak)throw new Error("Recorded breaks cannot also be marked no break taken");copy.out=signoff;copy.noBreak=copy.breaks.length===0}else throw new Error("Unknown time action");return copy}
export function hoursWorked(record:TimeRecord){if(!record.out)return null;const breakMs=record.breaks.reduce((sum,b)=>sum+Math.max(0,(b.end||b.start)-b.start),0);return {elapsedHours:(record.out.at-record.in.at)/3600000,breakHours:breakMs/3600000,recordedWorkHours:Math.max(0,(record.out.at-record.in.at-breakMs)/3600000)};}
export function paySummary(s:Shift){return {hourlyCents:s.baseCents+s.differentialCents+(s.urgentUnit==="hour"?s.urgentCents:0),shiftBonusCents:s.urgentUnit==="shift"?s.urgentCents:0}}

export function scopedEmployee(caller:string,office:boolean,requested?:string){return office&&requested?requested:caller}
export function canReadDocument(caller:string,owner:string,office:boolean){return caller===owner||office}
export function canPublishPayroll(office:boolean,kind:string){return !["paystub","w2"].includes(kind)||office}

export const instructionSections = {responsibilities:"Shift responsibilities",lab:"Lab access & contacts",xray:"X-ray company & phone",medication:"Pyxis / emergency box access",charting:"Skilled charting requirements",incident:"Fall / incident packet checklist",ehr:"Charting system (PCC / Matrix / other)",admission:"Admission checklist",administration:"Administration names & phone numbers",psych:"Facility psychiatric emergency procedure",other:"Other facility instructions"};
export function validateInstructions(value:unknown):Record<string,string>{if(!value||typeof value!=="object"||Array.isArray(value))throw new Error("Invalid shift instructions");const result:Record<string,string>={};for(const [key,text] of Object.entries(value)){if(!(key in instructionSections)||typeof text!=="string"||text.length>3000||text.split("\n").length>30)throw new Error("Use up to 30 lines / 3,000 characters per instruction section");result[key]=text.trim()}return result}
export function instructionItems(notes:Record<string,string>={}){return Object.entries(instructionSections).flatMap(([category,title])=>(notes[category]||"").split("\n").map(t=>t.trim()).filter(Boolean).map((text,index)=>({id:JSON.stringify([category,text,index]),category,title,text})))}
export function visibleShift(s:Shift,office:boolean,assigned:boolean){const copy={...s};if(!office&&!assigned)delete copy.notes;return copy}

export function shiftPresentation(status:string,shift:{urgent?:boolean;urgentCents?:number}){if(status==='cancelled')return {className:'availability-cancelled',label:'Facility Canceled'};if(status==='filled'||status==='accepted')return {className:'availability-booked',label:'Booked'};if(shift.urgent===true||(shift.urgentCents||0)>0)return {className:'availability-urgent',label:'Urgent · Available'};return {className:'availability-open',label:'Available'};}

export function validateSupervisorTitle(value:unknown):'RN'|'LPN'{if(value!=='RN'&&value!=='LPN')throw new Error('The signing supervisor must select RN or LPN beside their printed name.');return value;}
