import {encodeBytes,decodeBytes,hashBytes} from './encoding.ts';
export interface Storage {get<T>(key:string):Promise<T|undefined>;put(key:string,value:unknown):Promise<void>;delete(key:string):Promise<boolean>;}
type Snapshot={id:string;chunks:number;hash:string;bytes:number;at:number};
export class SnapshotStore {
 constructor(private storage:Storage){}
 async read(){const head=await this.storage.get<Snapshot>('nursing:head');if(!head)return null;return this.readSnapshot(head);}
 async readSnapshot(head:Snapshot){if(head.chunks<1||head.chunks>2048)throw new Error('Invalid Snapshot');let encoded='';for(let i=0;i<head.chunks;i++){const part=await this.storage.get<string>('nursing:snapshot:'+head.id+':'+i);if(typeof part!=='string')throw new Error('Incomplete Snapshot');encoded+=part;}const bytes=decodeBytes(encoded);if(bytes.length!==head.bytes||await hashBytes(bytes)!==head.hash)throw new Error('Snapshot Integrity Check Failed');return bytes;}
 async commit(bytes:Uint8Array){if(bytes.length>8*1024*1024)throw new Error('Records Storage Limit Reached; Contact The Agency');const encoded=encodeBytes(bytes),head:Snapshot={id:crypto.randomUUID(),chunks:Math.ceil(encoded.length/48000),hash:await hashBytes(bytes),bytes:bytes.length,at:Date.now()};let published=false;try{for(let i=0;i<head.chunks;i++)await this.storage.put('nursing:snapshot:'+head.id+':'+i,encoded.slice(i*48000,(i+1)*48000));const previous=await this.storage.get<Snapshot>('nursing:head');await this.storage.put('nursing:head',head);published=true;if(previous){try{const oldBackup=await this.storage.get<Snapshot>('nursing:previous');await this.storage.put('nursing:previous',previous);if(oldBackup)for(let i=0;i<oldBackup.chunks;i++)await this.storage.delete('nursing:snapshot:'+oldBackup.id+':'+i);}catch{/* Cleanup must never change whether a published transaction succeeded. */}}return head;}catch(error){if(!published)for(let i=0;i<head.chunks;i++)try{await this.storage.delete('nursing:snapshot:'+head.id+':'+i);}catch{}throw error;}}
}
