import {inactiveGuard} from '../security.ts';
import {identity,isOffice,db,sameOrigin,fail,limitedBody} from '../security.ts';
import {validateAbsenceReport,suspensionSummary,rewardExclusion,rewardYear} from '../../../lib/no-call-no-show.ts';
export const runtime='edge';
const json=(data:unknown)=>Response.json(data,{headers:{'Cache-Control':'no-store'}});
function text(x:unknown,max:number){if(typeof x!=='string'||x.length>max)throw new Error('Invalid entry');return x.trim()}
export async function GET(){const user=await identity();if(!user)return fail(401,'Sign in required');const denied=await inactiveGuard(user);if(denied)return denied;try{const d=db(),office=isOffice(user),email=user.email.toLowerCase();const grants=await d.prepare("SELECT facility FROM facility_access WHERE email=? AND active=1").bind(email).all<any>();const representative=!office&&grants.results.length>0;
const rows=await d.prepare("SELECT r.*,COALESCE(json_extract(z.data,'$.start'),r.submitted_at) AS infraction_at,p.data AS person_data,s.offense,s.days,s.ends_at FROM ncns_incidents r LEFT JOIN assignments a ON a.id=r.id LEFT JOIN live_shifts z ON z.id=a.shift_id LEFT JOIN applications p ON p.user_id=r.user_id LEFT JOIN ncns_suspensions s ON s.id=r.id WHERE (?=1 OR (?=0 AND r.user_id=?) OR (?=1 AND EXISTS(SELECT 1 FROM facility_access f WHERE f.email=? AND f.facility=r.facility AND f.active=1))) ORDER BY r.submitted_at DESC LIMIT 1001").bind(office?1:0,representative?1:0,user.userId,representative?1:0,email).all<any>();if(rows.results.length>1000)throw new Error('Incident list exceeds safe limit');
const assignments=office||representative?await d.prepare("SELECT a.id,a.user_id,s.data,p.data AS person_data FROM assignments a JOIN live_shifts s ON s.id=a.shift_id LEFT JOIN applications p ON p.user_id=a.user_id WHERE (a.state='accepted' OR (a.state='employee_cancelled' AND a.updated_at>=json_extract(s.data,'$.start'))) AND s.status!='cancelled' AND json_extract(s.data,'$.start')<=? AND NOT EXISTS(SELECT 1 FROM attendance t WHERE t.assignment_id=a.id AND json_extract(t.data,'$.in') IS NOT NULL) AND NOT EXISTS(SELECT 1 FROM ncns_incidents r WHERE r.id=a.id) AND (?=1 OR EXISTS(SELECT 1 FROM facility_access f WHERE f.email=? AND f.facility=json_extract(s.data,'$.facility') AND f.active=1)) ORDER BY a.updated_at DESC LIMIT 1001").bind(Date.now(),office?1:0,email).all<any>():{results:[]};if(assignments.results.length>1000)throw new Error('Assignment list exceeds safe limit');
const evidence=office||!representative?await d.prepare("SELECT e.incident_id,d.id,d.filename,d.created_at FROM ncns_evidence e JOIN documents d ON d.id=e.document_id JOIN ncns_incidents r ON r.id=e.incident_id WHERE ?=1 OR r.user_id=? ORDER BY d.created_at").bind(office?1:0,user.userId).all<any>():{results:[]};
const unlinked=office||!representative?await d.prepare("SELECT d.id,d.user_id,d.filename FROM documents d WHERE d.kind='absence_reason' AND (?=1 OR d.user_id=?) AND NOT EXISTS(SELECT 1 FROM ncns_evidence e WHERE e.document_id=d.id) ORDER BY d.created_at DESC LIMIT 1001").bind(office?1:0,user.userId).all<any>():{results:[]};if(unlinked.results.length>1000)throw new Error('Unlinked document list exceeds safe limit');
const history=await d.prepare("SELECT e.subject,e.action,e.data,e.created_at FROM workflow_events e JOIN ncns_incidents r ON r.id=e.subject WHERE (?=1 OR (?=0 AND r.user_id=?) OR (?=1 AND EXISTS(SELECT 1 FROM facility_access f WHERE f.email=? AND f.facility=r.facility AND f.active=1))) AND e.action!='ncns_evidence' ORDER BY e.created_at LIMIT 2001").bind(office?1:0,representative?1:0,user.userId,representative?1:0,email).all<any>();if(history.results.length>2000)throw new Error('History exceeds safe limit');
const name=(p:string|null)=>{const x=p?JSON.parse(p):{};return [x.firstName,x.lastName].filter(Boolean).join(' ')||'Employee'};
return json({office,representative,rewardExclusion:representative?undefined:rewardExclusion(rows.results.filter((r:any)=>r.status==='active'),user.userId,{start:Date.now(),end:Date.now()+1},Date.now()),suspension:representative?undefined:suspensionSummary(rows.results.filter((r:any)=>r.user_id===user.userId&&r.status==='active'),Date.now()),assignments:assignments.results.map((r:any)=>{const s=JSON.parse(r.data);return {id:r.id,name:name(r.person_data),facility:s.facility,start:s.start,end:s.end}}),incidents:rows.results.map((r:any)=>({id:r.id,userId:office?r.user_id:undefined,name:office||representative?name(r.person_data):undefined,facility:r.facility,status:r.status,report:JSON.parse(r.report),submitted_at:r.submitted_at,infraction_at:r.infraction_at,reward_end:rewardYear(r.infraction_at).end,review_note:r.review_note,version:r.version,offense:representative?undefined:r.offense,days:representative?undefined:r.days,ends_at:representative?undefined:r.ends_at,evidence:evidence.results.filter((e:any)=>e.incident_id===r.id),availableEvidence:unlinked.results.filter((e:any)=>e.user_id===r.user_id).map((e:any)=>({id:e.id,filename:e.filename})),history:history.results.filter((h:any)=>h.subject===r.id).map((h:any)=>({action:h.action,at:h.created_at,...JSON.parse(h.data)}))}))});
}catch(e){console.error('NCNS load failed',e);return fail(503,'Could not load absence records. Please retry.')}}
export async function POST(request:Request){const user=await identity();if(!user)return fail(401,'Sign in required');const denied=await inactiveGuard(user);if(denied)return denied;if(!sameOrigin(request))return fail(403,'Request origin rejected');try{const x=JSON.parse(new TextDecoder().decode(await limitedBody(request,12000))),action=text(x.action,30),d=db(),office=isOffice(user),now=Date.now();
if(action==='report'){const id=text(x.assignmentId,300),report=validateAbsenceReport(x.report);const a=await d.prepare("SELECT a.user_id,s.data FROM assignments a JOIN live_shifts s ON s.id=a.shift_id WHERE a.id=?").bind(id).first<any>();if(!a)return fail(404,'Assignment not found');const facility=JSON.parse(a.data).facility;if(!office&&!await d.prepare("SELECT id FROM facility_access WHERE email=? AND facility=? AND active=1").bind(user.email.toLowerCase(),facility).first())return fail(403,'You are not authorized for this facility');const results=await d.batch([
d.prepare("INSERT OR IGNORE INTO ncns_incidents(id,user_id,facility,status,report,submitted_by,submitted_at) SELECT a.id,a.user_id,json_extract(s.data,'$.facility'),'active',?,?,? FROM assignments a JOIN live_shifts s ON s.id=a.shift_id WHERE a.id=? AND (a.state='accepted' OR (a.state='employee_cancelled' AND a.updated_at>=json_extract(s.data,'$.start'))) AND s.status!='cancelled' AND json_extract(s.data,'$.start')<=? AND NOT EXISTS(SELECT 1 FROM attendance t WHERE t.assignment_id=a.id AND json_extract(t.data,'$.in') IS NOT NULL) AND (?=1 OR EXISTS(SELECT 1 FROM facility_access f WHERE f.email=? AND f.facility=json_extract(s.data,'$.facility') AND f.active=1))").bind(JSON.stringify(report),user.userId,now,id,now,office?1:0,user.email.toLowerCase()),audit(user.userId,id,'ncns_reported',{note:'Facility confirmed no call, no show; automatic suspension applied.'},now)]);if(!results[0].meta.changes)return fail(409,'Already reported, attendance recorded, assignment not eligible, or facility access changed. Refresh and contact Always Nursing.');return json({saved:true});}
if(action==='review'){if(!office)return fail(403,'Only Always Nursing staff can change or revoke a report');const id=text(x.id,300),note=text(x.note,2000),status=text(x.status,20);if(!note||!['active','revoked'].includes(status))throw new Error('Enter a correction or revocation reason');const row=await d.prepare("SELECT status,version FROM ncns_incidents WHERE id=?").bind(id).first<any>();if(!row)return fail(404,'Incident not found');const result=await d.batch([d.prepare("UPDATE ncns_incidents SET status=?,review_note=?,reviewed_by=?,reviewed_at=?,version=version+1 WHERE id=? AND version=?").bind(status,note,user.userId,now,id,x.version),audit(user.userId,id,'ncns_review',{from:row.status,to:status,note},now)]);if(!result[0].meta.changes)return fail(409,'Report changed. Refresh before reviewing.');return json({saved:true});}
if(action==='evidence'){const id=text(x.id,300),documentId=text(x.documentId,100);const result=await d.batch([d.prepare("INSERT OR IGNORE INTO ncns_evidence(document_id,incident_id,created_at) SELECT d.id,r.id,? FROM documents d JOIN ncns_incidents r ON r.user_id=d.user_id WHERE d.id=? AND r.id=? AND d.kind='absence_reason' AND (?=1 OR r.user_id=?) AND NOT EXISTS(SELECT 1 FROM facility_access WHERE email=? AND active=1 AND ?=0)").bind(now,documentId,id,office?1:0,user.userId,user.email.toLowerCase(),office?1:0),audit(user.userId,id,'ncns_evidence',{documentId},now)]);if(!result[0].meta.changes)return fail(403,'Document unavailable or already linked. Only the employee and Always Nursing may submit evidence.');return json({saved:true});}
return fail(400,'Unknown action');}catch(e){return fail(400,e instanceof Error?e.message:'Could not save absence record')}}
function audit(actor:string,subject:string,action:string,data:unknown,at:number){return db().prepare("INSERT INTO workflow_events(id,actor,subject,action,data,created_at) SELECT ?,?,?,?,?,? WHERE changes()=1").bind(crypto.randomUUID(),actor,subject,action,JSON.stringify(data),at)}
