import {shiftCalendarDate} from "../../../lib/facility-image.ts";
import {annualExpiry} from '../../../lib/onboarding.ts';
import {inactiveGuard} from '../security.ts';
import {identity,isOffice,db,sameOrigin,fail,limitedBody} from "../security.ts";
import {validateSupervisorTitle,validateInstructions,instructionItems,visibleShift,eligibility,validateLocation,validSignature,applyTimeAction,coreRequirements,scopedEmployee,type Shift,type Compliance,type TimeRecord,type Signoff} from "../../../lib/workflow.ts";
import {suspensionSummary} from "../../../lib/no-call-no-show.ts";
export const runtime="edge";
const json=(data:unknown)=>Response.json(data,{headers:{"Cache-Control":"no-store"}});
function string(v:unknown,max=1000){if(typeof v!=="string"||v.length>max)throw new Error("Invalid text entry");return v.trim()}
function parse(row:any){return row?{...row,data:JSON.parse(row.data)}:null}
export async function GET(request:Request){const user=await identity();if(!user)return fail(401,"Sign in required");const denied=await inactiveGuard(user);if(denied)return denied;const office=isOffice(user);try{const target=scopedEmployee(user.userId,office,new URL(request.url).searchParams.get("employee")||undefined);const d=db();const [shifts,assignments,times,messages,docs,contact,comp,people,history,checklists,suspensions]=await Promise.all([
 d.prepare("SELECT * FROM live_shifts ORDER BY created_at DESC LIMIT 200").all(),
 d.prepare("SELECT * FROM assignments WHERE user_id=? ORDER BY updated_at DESC LIMIT 200").bind(target).all(),
 d.prepare("SELECT * FROM attendance WHERE user_id=?").bind(target).all(),
 d.prepare("SELECT * FROM conversations WHERE user_id=? ORDER BY created_at DESC LIMIT 100").bind(target).all(),
 d.prepare("SELECT id,kind,filename,created_at FROM documents WHERE user_id=? ORDER BY created_at DESC LIMIT 300").bind(target).all(),
 d.prepare("SELECT value FROM settings WHERE key='staff_email'").first(),
 d.prepare("SELECT * FROM compliance WHERE user_id=?").bind(target).first(),
 office?d.prepare("SELECT user_id,email,data FROM applications ORDER BY updated_at DESC LIMIT 200").all():Promise.resolve({results:[]}),d.prepare("SELECT action,data,created_at FROM workflow_events WHERE actor=? ORDER BY created_at DESC LIMIT 100").bind(target).all(),d.prepare("SELECT a.shift_id,s.value FROM assignments a JOIN settings s ON s.key='checklist:'||a.id WHERE a.user_id=?").bind(target).all(),d.prepare("SELECT * FROM ncns_suspensions WHERE user_id=?").bind(target).all()]);
 const hire=await d.prepare("SELECT value FROM settings WHERE key=?").bind("employee_hired:"+target).first<{value:string}>();return json({target,office,hired:!!hire&&JSON.parse(hire.value).hired===true,suspension:suspensionSummary(suspensions.results as any,Date.now()),checklists:checklists.results.map((r:any)=>({...r,data:JSON.parse(r.value)})),shifts:shifts.results.map((r:any)=>{const row=parse(r);row.data=visibleShift(row.data,office,assignments.results.some((a:any)=>a.shift_id===row.id&&a.state==='accepted'));if(!office)delete row.assigned_user_id;return row}),assignments:assignments.results,times:times.results.map(parse),messages:messages.results.reverse().map((r:any)=>({...r,attachments:JSON.parse(r.attachments)})),documents:docs.results,staffEmail:contact?.value||"",compliance:parse(comp),people:people.results.map(parse),history:history.results.map(parse)});
 }catch(e){console.error("Workflow load failed",e);return fail(503,"Could not load staffing records. Please retry.")}}
export async function POST(request:Request){const user=await identity();if(!user)return fail(401,"Sign in required");const denied=await inactiveGuard(user);if(denied)return denied;if(!sameOrigin(request))return fail(403,"Request origin rejected");try{const raw=new TextDecoder().decode(await limitedBody(request,100000));if(raw.length>100000)return fail(413,"Request too large");const x=JSON.parse(raw),action=string(x.action,50),d=db(),office=isOffice(user),now=Date.now();
 if(action==="contact"){if(!office)return fail(403,"Office access required");const email=string(x.email,254);if(email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw new Error("Enter a valid staff email");await d.prepare("INSERT INTO settings(key,value) VALUES('staff_email',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").bind(email).run();return json({saved:true})}
 if(action==="message"){const target=office?string(x.employee,200):user.userId;if(!office)await d.prepare("INSERT OR IGNORE INTO applications(user_id,email,status,data,updated_at) VALUES(?,?,'draft','{}',?)").bind(user.userId,user.email,now).run();if(office&&!await d.prepare("SELECT user_id FROM applications WHERE user_id=?").bind(target).first())throw new Error("Choose an employee with an application record");const body=string(x.body,4000),attachments=Array.isArray(x.attachments)?x.attachments:[];if(attachments.length>10||attachments.some((a:unknown)=>typeof a!=="string"))throw new Error("Up to 10 attachments per message");if(!body&&!attachments.length)throw new Error("Write a message or add an attachment");for(const id of attachments){if(!await d.prepare("SELECT id FROM documents WHERE id=? AND user_id=? AND kind NOT IN ('paystub','w2')").bind(id,target).first())throw new Error("Attachment unavailable")}await d.prepare("INSERT INTO conversations(id,user_id,sender,body,attachments,created_at) VALUES(?,?,?,?,?,?)").bind(crypto.randomUUID(),target,office?"Office":"Employee",body,JSON.stringify(attachments),now).run();return json({saved:true})}
 if(action==="shiftCreate"){if(!office)return fail(403,"Office access required");const s=x.shift as Shift;if(!s||![s.start,s.end,s.baseCents,s.differentialCents,s.urgentCents,s.lat,s.lon,s.radius].every(Number.isFinite)||s.end<=s.start||s.start<now||s.end-s.start>86400000||[s.baseCents,s.differentialCents,s.urgentCents].some(v=>v<0||!Number.isInteger(v))||s.baseCents<=0||s.radius<25||s.radius>500||Math.abs(s.lat)>90||Math.abs(s.lon)>180||!['hour','shift'].includes(s.urgentUnit))throw new Error("Check shift times, pay, and facility location (radius 25–500 m)");if(s.urgent!==undefined&&typeof s.urgent!=='boolean')throw new Error('Choose urgent status');s.facilityType=string(s.facilityType||"Not specified",80);s.facilityPhone=string(s.facilityPhone||"",80);s.shiftPeriod=string(s.shiftPeriod||"Not specified",40);s.notes=validateInstructions(s.notes||{});s.facility=string(s.facility,150);s.address=string(s.address,300);s.state=string(s.state,2).toUpperCase();s.role=string(s.role,20).toUpperCase();s.source=string(s.source||"Direct entry",100);s.timeZone=string(s.timeZone,80);try{new Intl.DateTimeFormat('en-US',{timeZone:s.timeZone}).format()}catch{throw new Error("Choose a valid facility time zone")};if((s as any).shiftDate!==undefined&&((s as any).shiftDate!==shiftCalendarDate(s.start,s.timeZone)))throw new Error('Shift date must match the start date in the facility time zone');s.requirements=[...new Set([...coreRequirements,...(Array.isArray(s.requirements)?s.requirements:[])])];if(!s.facility||!s.address||!/^[A-Z]{2}$/.test(s.state)||!['RN','LPN','CNA'].includes(s.role)||s.requirements.some(k=>typeof k!=="string"||!/^\w{1,30}$/.test(k)))throw new Error("Complete facility, state and role");await d.prepare("INSERT INTO live_shifts(id,data,status,created_at) VALUES(?,?,'open',?)").bind(crypto.randomUUID(),JSON.stringify(s),now).run();return json({saved:true})}
 if(action==="compliance"){if(!office)return fail(403,"Office access required");const target=string(x.employee,200),c=x.compliance as Compliance;if(!c||!['RN','LPN','CNA'].includes(c.role)||!Array.isArray(c.states)||c.states.length>55||c.states.some(s=>!/^[A-Z]{2}$/.test(s))||!c.expires||Object.entries(c.expires).some(([k,v])=>!/^\w{1,30}$/.test(k)||!Number.isFinite(v)||v<now)||!c.sourceNote?.trim()||c.sourceNote.length>2000)throw new Error("Enter verified role, states, future expirations, and verification source details");for(const k of ['tb','bls','physical']){const date=c.issuedDates?.[k],limit=annualExpiry(date||'');if(!Number.isFinite(c.expires[k]))throw new Error('Enter verified '+k.toUpperCase()+' expiration');if(!date||!Number.isFinite(limit)||limit<now||Date.parse(date+'T00:00:00Z')>now)throw new Error(k.toUpperCase()+' must have a verified completion date within the last year');c.expires[k]=Math.min(c.expires[k],limit)}if(!await d.prepare("SELECT user_id FROM applications WHERE user_id=?").bind(target).first())throw new Error("Applicant not found");await d.prepare("INSERT INTO compliance(user_id,data,reviewed_by,updated_at) VALUES(?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET data=excluded.data,reviewed_by=excluded.reviewed_by,updated_at=excluded.updated_at").bind(target,JSON.stringify(c),user.userId,now).run();return json({saved:true})}
 const shiftRow=await d.prepare("SELECT * FROM live_shifts WHERE id=?").bind(string(x.shiftId,100)).first<any>();if(!shiftRow)return fail(404,"Shift not found");const s=JSON.parse(shiftRow.data) as Shift,assignmentId=`${shiftRow.id}:${user.userId}`;
 if(action==="shiftInstructions"){if(!office)return fail(403,"Office access required");if(x.version!==shiftRow.version)throw new Error("Shift instructions changed; reopen them before saving");const next={...s,facilityType:string(x.facilityType||"Not specified",80),facilityPhone:string(x.facilityPhone||"",80),shiftPeriod:string(x.shiftPeriod||"Not specified",40),notes:validateInstructions(x.notes)};const result=await d.prepare("UPDATE live_shifts SET data=?,version=version+1 WHERE id=? AND version=?").bind(JSON.stringify(next),shiftRow.id,shiftRow.version).run();if(!result.meta.changes)throw new Error("Shift changed; reopen instructions and retry");return json({saved:true})}
 if(action==="shiftCancel"){if(!office)return fail(403,"Office access required");const reason=string(x.reason,1000);if(!reason)throw new Error("Enter a cancellation reason");const cancelledData=JSON.stringify({...s,cancellationReason:reason});const results=await d.batch([
 d.prepare("UPDATE live_shifts SET status='cancelled',data=?,version=version+1 WHERE id=? AND version=? AND status!='cancelled' AND NOT EXISTS(SELECT 1 FROM attendance a JOIN assignments b ON b.id=a.assignment_id WHERE b.shift_id=? )").bind(cancelledData,shiftRow.id,shiftRow.version,shiftRow.id),
 d.prepare("UPDATE assignments SET state='facility_cancelled',updated_at=? WHERE shift_id=? AND state='accepted' AND EXISTS(SELECT 1 FROM live_shifts WHERE id=? AND status='cancelled')").bind(now,shiftRow.id,shiftRow.id)]);if(!results[0].meta.changes)throw new Error("Shift changed or an employee is clocked in; resolve attendance first");return json({saved:true})}
 const comp=await d.prepare("SELECT * FROM compliance WHERE user_id=?").bind(user.userId).first<any>();
 if(action==="accept"){const hiring=await d.prepare("SELECT value FROM settings WHERE key=?").bind("employee_hired:"+user.userId).first<{value:string}>();if(!hiring||JSON.parse(hiring.value).hired!==true)throw new Error("Preview only: Always Nursing must approve your hiring before you can accept shifts.");const suspension=await d.prepare("SELECT ends_at FROM ncns_suspensions WHERE user_id=? AND submitted_at<=? AND ends_at>? ORDER BY ends_at DESC LIMIT 1").bind(user.userId,now,now).first<any>();if(suspension)throw new Error(`Shift booking is suspended until ${new Date(suspension.ends_at).toISOString()}. Submit a valid reason in No Call, No Show document uploads; contact Always Nursing.`);if(await d.prepare("SELECT id FROM facility_reports WHERE kind='dnr' AND status='active' AND user_id=? AND facility=?").bind(user.userId,s.facility).first())throw new Error("An active DNR prevents booking this facility. Contact Always Nursing.");if(shiftRow.status!=="open"||shiftRow.assigned_user_id||s.start<=now)throw new Error("This shift is no longer available");const errors=eligibility(comp?JSON.parse(comp.data):null,s,now);if(errors.length)throw new Error(errors.join("; "));if(await d.prepare("SELECT assignment_id FROM attendance WHERE assignment_id=?").bind(assignmentId).first())throw new Error("This assignment already has time records");const results=await d.batch([
 d.prepare("UPDATE live_shifts SET status='filled',assigned_user_id=?,version=version+1 WHERE id=? AND status='open' AND assigned_user_id IS NULL AND version=? AND EXISTS(SELECT 1 FROM compliance WHERE user_id=? AND updated_at=?) AND EXISTS(SELECT 1 FROM settings WHERE key='employee_hired:'||? AND json_extract(value,'$.hired')=1) AND NOT EXISTS(SELECT 1 FROM assignments a JOIN live_shifts s ON s.id=a.shift_id WHERE a.user_id=? AND a.state='accepted' AND json_extract(s.data,'$.start')<? AND json_extract(s.data,'$.end')>?) AND NOT EXISTS(SELECT 1 FROM facility_reports r WHERE r.kind='dnr' AND r.status='active' AND r.user_id=? AND r.facility=json_extract(live_shifts.data,'$.facility')) AND NOT EXISTS(SELECT 1 FROM employee_status e WHERE e.user_id=? AND e.status IN ('quit','terminated')) AND NOT EXISTS(SELECT 1 FROM ncns_suspensions n WHERE n.user_id=? AND n.submitted_at<=? AND n.ends_at>?)").bind(user.userId,shiftRow.id,shiftRow.version,user.userId,comp.updated_at,user.userId,user.userId,s.end,s.start,user.userId,user.userId,user.userId,now,now),
 d.prepare("INSERT INTO assignments(id,shift_id,user_id,state,pay_snapshot,updated_at) SELECT ?,?,?,'accepted',?,? WHERE changes()=1 ON CONFLICT(id) DO UPDATE SET state='accepted',pay_snapshot=excluded.pay_snapshot,updated_at=excluded.updated_at").bind(assignmentId,shiftRow.id,user.userId,JSON.stringify({baseCents:s.baseCents,differentialCents:s.differentialCents,urgentCents:s.urgentCents,urgentUnit:s.urgentUnit}),now),auditStatement(user.userId,assignmentId,"accept",{},now)]);if(!results[0].meta.changes)throw new Error("Shift was claimed, conflicts with another assignment, credentials changed, or shift booking is suspended. Refresh and retry.");return json({saved:true})}
 const assignment=await d.prepare("SELECT * FROM assignments WHERE id=? AND user_id=?").bind(assignmentId,user.userId).first<any>();if(!assignment)return fail(403,"You do not have this assignment");
 if(action==="checklist"){if(assignment.state!=="accepted"||shiftRow.status==="cancelled")throw new Error("An accepted assignment is required");const valid=new Set(instructionItems(s.notes).map(i=>i.id));if(typeof x.item!=="string"||!valid.has(x.item)||typeof x.checked!=="boolean")throw new Error("Checklist item changed; reopen shift instructions");const key=`checklist:${assignmentId}`;const current=await d.prepare("SELECT value FROM settings WHERE key=?").bind(key).first<any>();const previous=current?.value;const progress=previous?JSON.parse(previous):{checked:{}};progress.checked[x.item]=x.checked;progress.updatedAt=now;const result=previous?await d.prepare("UPDATE settings SET value=? WHERE key=? AND value=? AND EXISTS(SELECT 1 FROM assignments WHERE id=? AND state='accepted') AND EXISTS(SELECT 1 FROM live_shifts WHERE id=? AND version=? AND status!='cancelled')").bind(JSON.stringify(progress),key,previous,assignmentId,shiftRow.id,shiftRow.version).run():await d.prepare("INSERT OR IGNORE INTO settings(key,value) SELECT ?,? WHERE EXISTS(SELECT 1 FROM assignments WHERE id=? AND state='accepted') AND EXISTS(SELECT 1 FROM live_shifts WHERE id=? AND version=? AND status!='cancelled')").bind(key,JSON.stringify(progress),assignmentId,shiftRow.id,shiftRow.version).run();if(!result.meta.changes)throw new Error("Checklist changed; refresh and retry");return json({saved:true})}
 if(action==="withdraw"||action==="cancel"){if(assignment.state!=="accepted")throw new Error("Assignment is not accepted");if(action==="withdraw"&&now>=s.start)throw new Error("Withdrawal is available only before shift start; contact the office");const reason=string(x.reason,1000);if(!reason)throw new Error("Enter a reason for the office");const results=await d.batch([
 d.prepare("UPDATE live_shifts SET status='open',assigned_user_id=NULL,version=version+1 WHERE id=? AND status='filled' AND assigned_user_id=? AND NOT EXISTS(SELECT 1 FROM attendance WHERE assignment_id=?)").bind(shiftRow.id,user.userId,assignmentId),
 d.prepare("UPDATE assignments SET state=?,updated_at=? WHERE id=? AND changes()=1").bind(action==="withdraw"?"withdrawn":"employee_cancelled",now,assignmentId),auditStatement(user.userId,assignmentId,action,{reason},now)]);if(!results[0].meta.changes)throw new Error("Cannot withdraw or cancel after clock-in; contact the office");return json({saved:true})}
 if(['clockIn','clockOut','breakStart','breakEnd'].includes(action)){if(assignment.state!=="accepted"||shiftRow.status==="cancelled")throw new Error("An active accepted assignment is required");const time=await d.prepare("SELECT * FROM attendance WHERE assignment_id=?").bind(assignmentId).first<any>();let signoff:Signoff|undefined;
 if(action==="clockIn"){if(await d.prepare("SELECT id FROM facility_reports WHERE kind='dnr' AND status='active' AND user_id=? AND facility=?").bind(user.userId,s.facility).first())throw new Error("An active facility DNR prevents clock-in. Contact Always Nursing.");const errors=eligibility(comp?JSON.parse(comp.data):null,s,now);if(errors.length)throw new Error(errors.join("; "));if(now<s.start-3600000||now>s.end)throw new Error("Clock-in opens one hour before start and closes at shift end");validateLocation(x.location,s,now)}
 if(action==="clockIn"||action==="clockOut"){const employeeName=string(x.employeeName,150),supervisorName=string(x.supervisorName,150);if(employeeName.split(/\s+/).length<2||supervisorName.split(/\s+/).length<2||!validSignature(x.signature))throw new Error("Employee and supervisor full names and a drawn supervisor signature are required");signoff={employeeName,supervisorName,supervisorTitle:validateSupervisorTitle(x.supervisorTitle),signature:x.signature,at:now,location:action==="clockIn"?x.location:undefined};}
 const updated=applyTimeAction(time?JSON.parse(time.data):null,action,now,signoff,x.noBreak);const write=!time?d.prepare("INSERT OR IGNORE INTO attendance(assignment_id,user_id,data,version) SELECT ?,?,?,0 WHERE EXISTS(SELECT 1 FROM live_shifts WHERE id=? AND status='filled' AND assigned_user_id=?) AND EXISTS(SELECT 1 FROM compliance WHERE user_id=? AND updated_at=?) AND NOT EXISTS(SELECT 1 FROM facility_reports WHERE kind='dnr' AND status='active' AND user_id=? AND facility=?)").bind(assignmentId,user.userId,JSON.stringify(updated),shiftRow.id,user.userId,user.userId,comp?.updated_at??0,user.userId,s.facility):d.prepare("UPDATE attendance SET data=?,version=version+1 WHERE assignment_id=? AND version=?").bind(JSON.stringify(updated),assignmentId,time.version);const results=await d.batch([write,auditStatement(user.userId,assignmentId,action,{noBreak:updated.noBreak||false},now)]);if(!results[0].meta.changes)throw new Error("Time record changed or shift is unavailable; refresh before retrying");return json({saved:true})}
 return fail(400,"Unknown action");
 }catch(e){return fail(400,e instanceof Error?e.message:"Could not save changes")}}
function auditStatement(actor:string,subject:string,action:string,data:unknown,at:number){return db().prepare("INSERT INTO workflow_events(id,actor,subject,action,data,created_at) SELECT ?,?,?,?,?,? WHERE changes()=1").bind(crypto.randomUUID(),actor,subject,action,JSON.stringify(data),at)}
